/* The Cairn — Test station. Defines window.renderTest(form). Relies on app.js globals: form, step, rstep. */
(function(){
  var cur=null;
  function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}
  function f2(v){return (Math.round(v*100)/100).toFixed(2)}
  function ok(got,exp){var g=parseFloat(String(got).trim().replace(',','.'));if(isNaN(g))return false;return Math.abs(g-exp)<=Math.max(0.05,Math.abs(exp)*0.02)}
  function genMean(){var a=[];for(var i=0;i<5;i++)a.push(rnd(1,15));var s=a.slice().sort(function(x,y){return x-y});var sum=a.reduce(function(p,c){return p+c},0);return{form:1,a:a,sorted:s,n:5,sum:sum,mean:sum/5,median:s[2]}}
  function genPos(){var a=[];for(var i=0;i<7;i++)a.push(rnd(1,12));a.sort(function(x,y){return x-y});var counts={},hasDup=false;a.forEach(function(v){counts[v]=(counts[v]||0)+1;if(counts[v]>1)hasDup=true});if(!hasDup){a[1]=a[0]}a.sort(function(x,y){return x-y});counts={};a.forEach(function(v){counts[v]=(counts[v]||0)+1});var mode=a[0],best=0;Object.keys(counts).forEach(function(k){if(counts[k]>best){best=counts[k];mode=parseFloat(k)}});return{form:2,a:a,n:7,median:a[3],q1:a[1],q3:a[5],iqr:a[5]-a[1],mode:mode}}
  function genVar(){var a=[];for(var i=0;i<4;i++)a.push(rnd(2,14));var sum=a.reduce(function(p,c){return p+c},0),mean=sum/4;var pile=a.reduce(function(p,c){return p+(c-mean)*(c-mean)},0);var svar=pile/3;return{form:3,a:a,n:4,sum:sum,mean:mean,pile:pile,svar:svar,sstd:Math.sqrt(svar)}}
  function genPair(){var x,y,mx,my,sp,sx2,sy2,tries=0;do{x=[];y=[];for(var i=0;i<4;i++){x.push(rnd(1,10));y.push(rnd(1,10))}mx=x.reduce(function(p,c){return p+c},0)/4;my=y.reduce(function(p,c){return p+c},0)/4;sp=0;sx2=0;sy2=0;for(var j=0;j<4;j++){sp+=(x[j]-mx)*(y[j]-my);sx2+=(x[j]-mx)*(x[j]-mx);sy2+=(y[j]-my)*(y[j]-my)}tries++}while((sx2===0||sy2===0)&&tries<40);var sx=Math.sqrt(sx2/3),sy=Math.sqrt(sy2/3),sxy=sp/3;return{x:x,y:y,n:4,mx:mx,my:my,sp:sp,sxy:sxy,sx:sx,sy:sy,sxsy:sx*sy,r:(sx===0||sy===0)?0:sxy/(sx*sy)}}
  function genCov(){var d=genPair();d.form=4;return d}
  function genCorr(){var d=genPair();d.form=5;return d}
  function gen(f){return f===1?genMean():f===2?genPos():f===3?genVar():f===4?genCov():genCorr()}
  var IST='background:#0a0a0b;border:1px solid #27272a;border-radius:6px;color:#fafafa;padding:8px 10px;font-family:inherit;font-size:.95rem;width:140px;margin-bottom:6px';
  function fieldRow(label,id){return '<div class="input-section-label">'+label+'</div><input id="'+id+'" type="text" inputmode="decimal" placeholder="your answer" style="'+IST+'">'}
  function dataRow(label,arr){return '<tr><th>'+label+'</th><td>'+arr.join('</td><td>')+'</td></tr>'}
  function controls(){return '<div class="btn-row"><button class="action-btn" onclick="cairnCheck()">Check</button><button class="action-btn secondary" onclick="cairnNew()">New problem</button></div><div id="cairn-feedback" style="margin-top:16px"></div></div>'}
  function head(title,prompt){return '<div class="step-content"><h3>Test — your turn</h3><p style="color:var(--accent);font-weight:600">'+title+'</p><p>'+prompt+'</p>'}
  window.renderTest=function(f){if(!cur||cur.form!==f)cur=gen(f);var el=document.getElementById('step-container');if(!el)return;var h='';if(f===1){h=head('Find the centre.','For this sample, give the <strong>mean X̄</strong> (2 decimals) and the <strong>median</strong>.');h+='<div class="input-section-label">Sample, n = 5</div><table class="data-table"><tbody>'+dataRow('x',cur.a)+'</tbody></table>';h+=fieldRow('Mean X̄','t-mean')+fieldRow('Median','t-median')}else if(f===2){h=head('Read the landmarks.','For this sample (sort it first), give the <strong>median</strong>, the <strong>IQR</strong>, and the <strong>mode</strong>.');h+='<div class="input-section-label">Sample, n = 7 (unsorted)</div><table class="data-table"><tbody>'+dataRow('x',cur.a)+'</tbody></table>';h+=fieldRow('Median','t-median')+fieldRow('IQR','t-iqr')+fieldRow('Mode','t-mode')}else if(f===3){h=head('Measure the spread.','This is a <strong>sample</strong> (n = 4). Give the sample variance <strong>Sₓ²</strong> and standard deviation <strong>Sₓ</strong> (2 decimals).');h+='<div class="input-section-label">Sample, n = 4</div><table class="data-table"><tbody>'+dataRow('x',cur.a)+'</tbody></table>';h+=fieldRow('Sample variance Sₓ²','t-var')+fieldRow('Standard deviation Sₓ','t-std')}else if(f===4){h=head('Do they move together?','Paired <strong>sample</strong> (n = 4). Give the covariance <strong>Sₓᵧ</strong> (2 decimals).');h+='<div class="input-section-label">Paired sample, n = 4</div><table class="data-table"><tbody>'+dataRow('x',cur.x)+dataRow('y',cur.y)+'</tbody></table>';h+=fieldRow('Covariance Sₓᵧ','t-cov')}else{h=head('How tight is the link?','Paired <strong>sample</strong> (n = 4). Give the correlation <strong>Rₓᵧ</strong> (2 decimals).');h+='<div class="input-section-label">Paired sample, n = 4</div><table class="data-table"><tbody>'+dataRow('x',cur.x)+dataRow('y',cur.y)+'</tbody></table>';h+=fieldRow('Correlation Rₓᵧ','t-r')}h+=controls();el.innerHTML=h};
  function feedback(good,html){var fb=document.getElementById('cairn-feedback');if(!fb)return;var color=good?'#22c55e':'#ef4444';var label=good?'Correct — the stones line up.':'Not quite — walk it again:';fb.innerHTML='<div style="border:1px solid '+color+'40;background:'+color+'10;border-radius:8px;padding:14px 18px"><div style="color:'+color+';font-weight:600;margin-bottom:8px;font-size:.9rem">'+label+'</div><div style="color:#a1a1aa;font-size:.85rem;line-height:1.9;font-family:monospace">'+html+'</div></div>'}
  window.cairnNew=function(){cur=gen(form);step=5;rstep()};
  window.cairnCheck=function(){if(!cur)return;var f=cur.form;if(f===1){var good=ok(document.getElementById('t-mean').value,cur.mean)&&ok(document.getElementById('t-median').value,cur.median);feedback(good,'X̄ = ('+cur.a.join(' + ')+') ÷ 5 = '+cur.sum+' ÷ 5 = <strong>'+f2(cur.mean)+'</strong><br>sorted: '+cur.sorted.join(', ')+'<br>median = position (5+1)/2 = 3rd value = <strong>'+cur.median+'</strong>')}else if(f===2){var good=ok(document.getElementById('t-median').value,cur.median)&&ok(document.getElementById('t-iqr').value,cur.iqr)&&ok(document.getElementById('t-mode').value,cur.mode);feedback(good,'sorted: '+cur.a.join(', ')+'<br>median = position (7+1)/2 = 4th = <strong>'+cur.median+'</strong><br>Q1 = position (7+1)/4 = 2nd = '+cur.q1+', Q3 = position 3(7+1)/4 = 6th = '+cur.q3+'<br>IQR = '+cur.q3+' − '+cur.q1+' = <strong>'+cur.iqr+'</strong><br>mode = most frequent = <strong>'+cur.mode+'</strong>')}else if(f===3){var good=ok(document.getElementById('t-var').value,cur.svar)&&ok(document.getElementById('t-std').value,cur.sstd);var sqs=cur.a.map(function(c){return '('+c+'−'+f2(cur.mean)+')²'}).join(' + ');feedback(good,'X̄ = '+cur.sum+' ÷ 4 = <strong>'+f2(cur.mean)+'</strong><br>pile = '+sqs+' = <strong>'+f2(cur.pile)+'</strong><br>Sₓ² = pile ÷ (n−1) = '+f2(cur.pile)+' ÷ 3 = <strong>'+f2(cur.svar)+'</strong><br>Sₓ = √'+f2(cur.svar)+' = <strong>'+f2(cur.sstd)+'</strong>')}else if(f===4){var good=ok(document.getElementById('t-cov').value,cur.sxy);var prods=cur.x.map(function(xv,i){return '('+xv+'−'+f2(cur.mx)+')('+cur.y[i]+'−'+f2(cur.my)+')'}).join(' + ');feedback(good,'X̄ = <strong>'+f2(cur.mx)+'</strong>, Ȳ = <strong>'+f2(cur.my)+'</strong><br>pile = '+prods+' = <strong>'+f2(cur.sp)+'</strong><br>Sₓᵧ = pile ÷ (n−1) = '+f2(cur.sp)+' ÷ 3 = <strong>'+f2(cur.sxy)+'</strong>')}else{var good=ok(document.getElementById('t-r').value,cur.r);feedback(good,'X̄ = '+f2(cur.mx)+', Ȳ = '+f2(cur.my)+'<br>Sₓᵧ = <strong>'+f2(cur.sxy)+'</strong><br>Sₓ = '+f2(cur.sx)+', Sᵧ = '+f2(cur.sy)+', Sₓ·Sᵧ = '+f2(cur.sxsy)+'<br>Rₓᵧ = Sₓᵧ ÷ (Sₓ·Sᵧ) = '+f2(cur.sxy)+' ÷ '+f2(cur.sxsy)+' = <strong>'+f2(cur.r)+'</strong>')}};
})();
