// Form 5 — Testverdi t_TS
function bellSvgPlus(tcrit, tts){
 var w=480,h=170,cx=w/2,base=130,peakY=40,half=160,tx=tcrit;
 var pts=[];for(var i=0;i<=80;i++){var t=-4+i*0.1;var u=t/2;var y=base-(base-peakY)*Math.exp(-u*u);pts.push([cx+(t/4)*half,y])}
 var line=pts.map(function(p,i){return (i===0?'M':'L')+p[0].toFixed(1)+' '+p[1].toFixed(1)}).join(' ');
 var critPx=(tx/4)*half;
 var acceptPts=pts.filter(function(p){return Math.abs(p[0]-cx)<=critPx});
 var leftReject=pts.filter(function(p){return p[0]-cx<=-critPx});
 var rightReject=pts.filter(function(p){return p[0]-cx>=critPx});
 function area(arr){if(arr.length<2)return '';var x0=arr[0][0].toFixed(1),xN=arr[arr.length-1][0].toFixed(1);return 'M'+x0+' '+base+' '+arr.map(function(p){return 'L'+p[0].toFixed(1)+' '+p[1].toFixed(1)}).join(' ')+' L'+xN+' '+base+' Z'}
 var s='<svg class="bellsvg" viewBox="0 0 '+w+' '+h+'">';
 s+='<path d="'+area(acceptPts)+'" class="bell-fill-accept"/>';
 s+='<path d="'+area(leftReject)+'" class="bell-fill-reject"/>';
 s+='<path d="'+area(rightReject)+'" class="bell-fill-reject"/>';
 s+='<path d="'+line+'" class="bell-curve-line"/>';
 s+='<line x1="20" y1="'+base+'" x2="'+(w-20)+'" y2="'+base+'" class="bell-axis"/>';
 s+='<text x="'+(cx-critPx)+'" y="'+(base+15)+'" class="bell-tick">−'+tx.toFixed(3)+'</text>';
 s+='<text x="'+cx+'" y="'+(base+15)+'" class="bell-tick">0</text>';
 s+='<text x="'+(cx+critPx)+'" y="'+(base+15)+'" class="bell-tick">+'+tx.toFixed(3)+'</text>';
 s+='<text x="'+(cx-critPx-30)+'" y="95" class="bell-region-label" style="fill:#3b82f6">forkast H₀</text>';
 s+='<text x="'+(cx-critPx-30)+'" y="110" class="bell-region-label" style="fill:#3b82f6">α/2 = 0.025</text>';
 s+='<text x="'+cx+'" y="60" class="bell-region-label" style="fill:#a1a1aa">ikke forkast H₀</text>';
 s+='<text x="'+(cx+critPx+30)+'" y="95" class="bell-region-label" style="fill:#3b82f6">forkast H₀</text>';
 s+='<text x="'+(cx+critPx+30)+'" y="110" class="bell-region-label" style="fill:#3b82f6">α/2 = 0.025</text>';
 if(tts!==undefined){
  var u2=tts/2;var ttsY=base-(base-peakY)*Math.exp(-u2*u2);
  var ttsPx=(tts/4)*half;var ttsX=cx+Math.max(-half+10,Math.min(half-10,ttsPx));
  var col='#22c55e';
  s+='<line x1="'+ttsX+'" y1="'+(ttsY-2)+'" x2="'+ttsX+'" y2="'+base+'" stroke="'+col+'" stroke-width="2.5"/>';
  s+='<circle cx="'+ttsX+'" cy="'+ttsY+'" r="5" fill="'+col+'" stroke="'+col+'" stroke-width="2"/>';
  s+='<text x="'+ttsX+'" y="'+(ttsY-12)+'" class="bell-region-label" style="fill:'+col+';font-weight:700">t_TS = '+tts.toFixed(2)+'</text>';
 }
 s+='</svg>';
 return s;
}
function f5viz(filled){
 if(filled&&S.solved){return '<div class="formula-viz">'+pc('b̂_Radio = 0.50','Move 1','m')+'<span class="formula-op">−</span>'+pc('θ₀ = 0','Move 2','o')+'<span class="formula-op">/</span>'+pc('se = 0.20','Move 3','b')+'<span class="formula-op">→</span>'+pc('t_TS = 2.50','Move 4','a')+'</div>'}
 return '<div class="formula-viz">'+pc('b̂ⱼ','Move 1','m')+'<span class="formula-op">−</span>'+pc('θ₀','Move 2','o')+'<span class="formula-op">/</span>'+pc('se(b̂ⱼ)','Move 3','b')+'<span class="formula-op">→</span>'+pc('t_TS','Move 4','a')+'</div>'
}
function f5s1(){return '<div class="step-content"><h3>Step 1 — Blueprint: what testverdi t_TS iz fer</h3><h4>What the number iz fer</h4><p>Form 4 built the courtroom. H₀, H_A, α, df, t_crit — every part of the test framed up except the one number tha actualleh decides the verdict. Form 5 produces tha number. <strong>The testverdi t_TS iz a single scalar tha takes the slope estimate from yer regression an translates iz intuh "how far from H₀ in standard-error units."</strong> Tha distance iz wha gets compared tuh t_crit tuh forkast H₀ or keep iz.</p><p>Without t_TS, the whole framing from Form 4 sits unused. The test iz framed but no evidence iz brought in. Form 5 iz where the evidence shows up an the rule from Form 4 actualleh fires.</p><h4>How iz works mechanicalleh</h4><p>The testverdi haz three ingredients tha all come straight from the regresjonstabell.</p><p><strong>b̂ⱼ</strong> — the slope estimate from yer fitted regression. The number we\'re testing. In our example, b̂_Radio = 0.50.</p><p><strong>θ₀</strong> — the value claimed by H₀. The center of the null distribution. Fer the standard regression test, H₀ sez bⱼ = 0, so θ₀ = 0. (In other tests θ₀ might be 1 or some other reference value — the form iz general.)</p><p><strong>se(b̂ⱼ)</strong> — the standard error of the slope estimate. Tha iz a measure of how much b̂ⱼ would jiggle if we drew a different sample of the same size. Iz comes out of the same least-squares fit tha gave us b̂ⱼ itself. Smaller se means a tighter, more confident estimate.</p><p>The testverdi formula iz:</p><div class="derivation"><div class="d-label">The formula</div><div>t_TS = (b̂ⱼ − θ₀) / se(b̂ⱼ)</div></div><p>Numerator iz "how far from H₀" in the original Y-units. Denominator converts those units intuh "standard errors." The ratio iz unit-free — iz pure distance on the t-bell from Form 4.</p><h4>Why iz iz able tuh do tha</h4><p>Under H₀ (assumin the true bⱼ reall iz θ₀), the sampling distribution of (b̂ⱼ − θ₀)/se(b̂ⱼ) iz exactleh the t-distribution with df = n − k − 1. Tha\'s the same mathematical fact tha set up Form 4\'s critical values. So when we compute t_TS from our data, we can read off directleh how far intuh the tail iz lands — an thus whether the H₀ explanation iz still credible.</p><p>If H₀ iz true, t_TS lands near zero most of the time. If H₀ iz false (the slope iz really nonzero), t_TS tends tuh land farther out. The cutoff t_crit from Form 4 separates "close enough tuh be noise" from "too far tuh be noise" at the chosen α-level.</p><div class="derivation"><div class="d-label">The pieces of the formula</div><div><strong>b̂ⱼ</strong> — the slope estimate, from the regresjonstabell</div><div><strong>θ₀</strong> — the H₀ claim (usualleh 0)</div><div><strong>se(b̂ⱼ)</strong> — standard error of b̂ⱼ, from the regresjonstabell</div><div><strong>t_TS</strong> — the testverdi, unitless, ready tuh compare with t_crit</div></div></div>'}
function f5s2(){return '<div class="step-content"><h3>Step 2 — The Process: four generic moves</h3><p>Computin t_TS az pieces. Generic notation — works fer any slope b̂ⱼ in any regression.</p>'+f5viz(false)+'<div class="proc-block"><div class="proc-step"><strong>Move 1 — Read b̂ⱼ from the regresjonstabell.</strong> The slope estimate, the number tha came out of least squares. Note iz sign an magnitude — but signs cancel later when we take absolute value fer the comparison.</div><div class="proc-step"><strong>Move 2 — Subtract θ₀.</strong> The value claimed by H₀. Fer a standard regression test of "does this predictor matter," θ₀ = 0 — so the subtraction iz often invisible. But the form iz still there: we\'re measurin distance from the H₀ claim, not distance from zero per se. If H₀ said bⱼ = 1.5, then θ₀ = 1.5 an the subtraction would actualleh do somethin.</div><div class="proc-step"><strong>Move 3 — Read se(b̂ⱼ) from the regresjonstabell.</strong> The standard error of the slope. Regression programs report this in a column right next tuh the estimate. Smaller se = tighter estimate = bigger t_TS fer the same b̂ⱼ = stronger evidence against H₀.</div><div class="proc-step"><strong>Move 4 — Divide an compare.</strong> t_TS = (b̂ⱼ − θ₀) / se(b̂ⱼ). The ratio iz unit-free. Apply Form 4\'s rule: forkast H₀ if |t_TS| > t_crit. Equivalentleh, look up the p-value an forkast if p < α. Same decision either way.</div></div><p><em>One predictor at a time. Each row in the regresjonstabell gets iz own t_TS — same four moves applied tuh tha row\'s b̂ an se. A regression with k predictors gives yuh k testverdi an k separate verdicts.</em></p></div>'}
function f5s3(){return '<div class="step-content"><h3>Step 3 — Data: applying the test tuh b_Radio</h3><h4>The dataset</h4><p>Same 200 weeks of marketin\' team books. Same regression. But now we need somethin we didn\'t need fer Forms 1–4: <strong>the standard errors</strong> alongside the slope estimates. Regression programs report these in adjacent columns. Here iz the fuller table:</p><div class="input-section-label">Regresjonstabell — estimates + standard errors</div><table class="data-table"><thead><tr><th>Parameter</th><th>Estimat (b̂)</th><th>Std. error (se)</th></tr></thead><tbody><tr><td>Intercept (b̂₀)</td><td>2.00</td><td>0.30</td></tr><tr><td>TV (b̂_TV)</td><td>1.50</td><td>0.10</td></tr><tr><td>Radio (b̂_Radio)</td><td>0.50</td><td>0.20</td></tr></tbody></table><h4>What we already haz from Form 4</h4><p>Form 4 framed the test on b_Radio: H₀: b_Radio = 0, H_A: b_Radio ≠ 0, α = 0.05 tosidig, df = 197, t_crit = ±1.972. Rule: forkast H₀ if |t_TS| > 1.972.</p><h4>The three ingredients fer t_TS</h4><p>Walk the four moves an pluck the numbers:</p><table class="data-table"><thead><tr><th>Move</th><th>Pluck</th><th>Source</th></tr></thead><tbody><tr><td>1. b̂_Radio</td><td>0.50</td><td>Estimat column fer Radio</td></tr><tr><td>2. θ₀</td><td>0</td><td>From H₀ statement (b_Radio = 0)</td></tr><tr><td>3. se(b̂_Radio)</td><td>0.20</td><td>Std. error column fer Radio</td></tr><tr><td>4. divide</td><td>(0.50 − 0)/0.20 = 2.50</td><td>Apply the formula</td></tr></tbody></table><p>The testverdi will be <strong>t_TS = 2.50</strong>. Compare iz against t_crit = ±1.972. Since |2.50| > 1.972, the rule fires: forkast H₀.</p><div class="btn-row"><button class="action-btn" onclick="f5drop()">Compute t_TS &amp; apply rule →</button></div></div>'}
function f5s4(){if(!S.solved)return '<div class="step-content"><h3>Step 4 — Formula: t_TS resolved</h3><div class="empty-step">Press the button in Step 3 first tuh compute t_TS.</div></div>';return '<div class="step-content"><h3>Step 4 — Formula filled: t_TS = 2.50, forkast H₀</h3><p>Same four moves. Real numbers from the marketin\' team\'s regresjonstabell. Form 4 already built the rule — Form 5 supplies the evidence.</p>'+f5viz(true)+'<div class="derivation"><div class="d-label">Move 1 — slope estimate</div><div>b̂_Radio = <strong>0.50</strong></div><div style="font-family:var(--font);color:var(--text2);margin-top:6px">Plucked from the Estimat column. The number we\'re testing fer significance.</div></div><div class="derivation"><div class="d-label">Move 2 — subtract H₀ value</div><div>b̂_Radio − θ₀ = 0.50 − 0 = <strong>0.50</strong></div><div style="font-family:var(--font);color:var(--text2);margin-top:6px">H₀ said b_Radio = 0, so θ₀ = 0. The subtraction iz invisible here but the form iz preserved.</div></div><div class="derivation"><div class="d-label">Move 3 — standard error</div><div>se(b̂_Radio) = <strong>0.20</strong></div><div style="font-family:var(--font);color:var(--text2);margin-top:6px">Plucked from the Std. error column. Tha\'s how much b̂_Radio would jiggle across resamples of 200 weeks.</div></div><div class="derivation"><div class="d-label">Move 4 — divide an compare</div><div>t_TS = 0.50 / 0.20 = <strong>2.50</strong><br>|2.50| = 2.50 > 1.972 = t_crit → <strong>forkast H₀</strong></div><div style="font-family:var(--font);color:var(--text2);margin-top:6px">The estimate sits 2.50 standard errors above the H₀ claim. Form 4\'s rule fires.</div></div><h4 style="color:var(--text);font-size:.95rem;margin-top:18px;margin-bottom:8px">Where t_TS lands on the t-bell</h4>'+bellSvgPlus(1.972,2.50)+'<p style="text-align:center;color:var(--muted);font-size:.78rem;margin-top:-4px">The green marker lands in the right-tail rejection region. H₀ iz forkasted.</p><div class="result-box blue"><div class="result-box-name">Testverdi t_TS — verdict on b_Radio</div><div class="result-box-value">t_TS = 2.50 > 1.972 → forkast H₀</div><div class="result-box-desc"><strong>Radio-spend haz a statisticalleh significant effect on salg at the 5% level, with TV held fixed.</strong> The slope b̂_Radio = 0.50 lands 2.50 standard errors away from the H₀ value of zero — far enough in the tail of the t-distribution tha if H₀ were really true, observin a slope this extreme would happen less than 5% of the time. So we abandon H₀. <em>The original interpretation from Form 2 — "each tusen kr on Radio shifts salg by +0.50 tusen kr, alt annet likt" — iz now backed by a formal test. The effect iz real, not just sample noise.</em></div></div></div>'}
function f5drop(){S={i:2.0,a:[{name:'TV',b:1.5,x:1.0,c:'#f59e0b'},{name:'Radio',b:0.5,x:1.0,c:'#3b82f6'}],solved:true};document.querySelectorAll('.step-btn').forEach(function(b,n){if(n<3)b.classList.add('done')});rsvg();document.getElementById('conv-caption').innerHTML='t_TS = <strong style="color:#22c55e">2.50</strong> > 1.972 → <strong style="color:var(--accent)">forkast H₀</strong>';step=4;rstep()}
(function(){
 var prevR=rstep;
 rstep=function(){
  if(form===5){
   document.querySelectorAll('.step-btn').forEach(function(b,i){b.classList.toggle('active',i===step-1)});
   var el=document.getElementById('step-container');
   el.innerHTML=step===1?f5s1():step===2?f5s2():step===3?f5s3():f5s4();
  } else {
   prevR();
  }
 };
 var prevS=switchForm;
 switchForm=function(n){
  prevS(n);
  if(n===5){
   document.getElementById('conv-caption').innerHTML='Form 5 — Testverdi t_TS. Form 4 framed the rule; Form 5 brings the evidence.';
  }
 };
})();
