// HSM126 — Gå formelen (regn det ut). Kapittel 1 — Beskrivende statistikk.
var QG1 = [
{chapter:"Kap 1", correct:"B",
 q:String.raw`Datasettet (sortert): 3, 5, 5, 8, 10, 11, 14 \((n=7)\). <strong>Regn ut</strong> medianen (formel 1.1).`,
 a:String.raw`5`, b:String.raw`8`, c:String.raw`7`, d:String.raw`10`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 8.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Posisjon \(\frac{n+1}{2}=\frac{8}{2}=4\).</div><div class="proc-step"><strong>2 —</strong> Les av 4. plass: 3, 5, 5, <strong>8</strong>, 10, 11, 14 → 8.</div></div><div class="walk-note">Midtpunktet — like mange under som over.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Samme sett 3, 5, 5, 8, 10, 11, 14 \((n=7)\). <strong>Regn ut</strong> 1. kvartil \(Q_1\) (formel 1.2).`,
 a:String.raw`5`, b:String.raw`3`, c:String.raw`8`, d:String.raw`2`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 5.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Posisjon \(\frac{n+1}{4}=\frac{8}{4}=2\).</div><div class="proc-step"><strong>2 —</strong> Les av 2. plass: 3, <strong>5</strong>, 5, 8, … → 5.</div></div><div class="walk-note">En fjerdedel ligger på eller under denne verdien.</div>`},
{chapter:"Kap 1", correct:"C",
 q:String.raw`Samme sett \((n=7)\). <strong>Regn ut</strong> 3. kvartil \(Q_3\) (formel 1.3).`,
 a:String.raw`10`, b:String.raw`14`, c:String.raw`11`, d:String.raw`8`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — 11.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Posisjon \(\frac{3(n+1)}{4}=\frac{24}{4}=6\).</div><div class="proc-step"><strong>2 —</strong> Les av 6. plass: … 10, <strong>11</strong>, 14 → 11.</div></div><div class="walk-note">Tre fjerdedeler ligger under.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`I settet 3, 5, 5, 8, 10, 11, 14 — <strong>regn ut</strong> modus (formel 1.4).`,
 a:String.raw`8`, b:String.raw`5`, c:String.raw`14`, d:String.raw`3`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 5.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Tell forekomstene: 5 går igjen to ganger, alle andre én → modus = 5.</div></div><div class="walk-note">Typetallet — trenger ikke ligge i midten.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Datasett 2, 4, 6, 8, 10 \((n=5)\). <strong>Regn ut</strong> gjennomsnittet \(\bar X\) (formel 1.5).`,
 a:String.raw`5`, b:String.raw`6`, c:String.raw`30`, d:String.raw`4`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 6.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Summer: \(2+4+6+8+10=30\).</div><div class="proc-step"><strong>2 —</strong> Del på \(n\): \(\frac{30}{5}=6\).</div></div><div class="walk-note">Tyngdepunktet i dataene.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Utvalget 2, 4, 6, 8, 10 har \(\bar X=6\). <strong>Regn ut</strong> utvalgsvariansen \(S_X^2\) (formel 1.6).`,
 a:String.raw`8`, b:String.raw`10`, c:String.raw`40`, d:String.raw`6,32`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 10.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Avvik: \(-4,\ -2,\ 0,\ 2,\ 4\).</div><div class="proc-step"><strong>2 —</strong> Kvadrer: \(16,\ 4,\ 0,\ 4,\ 16\).</div><div class="proc-step"><strong>3 —</strong> Summer: \(40\).</div><div class="proc-step"><strong>4 —</strong> Del på \(n-1=4\): \(\frac{40}{4}=10\).</div></div><div class="walk-note">Utvalg → del på \(n-1\), ikke \(n\).</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Tenk deg at 2, 4, 6, 8, 10 er <em>hele populasjonen</em>. <strong>Regn ut</strong> populasjonsvariansen \(\sigma^2\) (formel 1.7).`,
 a:String.raw`8`, b:String.raw`10`, c:String.raw`40`, d:String.raw`16`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 8.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Sum av kvadrerte avvik: \(40\) (som før).</div><div class="proc-step"><strong>2 —</strong> Del på \(n=5\): \(\frac{40}{5}=8\).</div></div><div class="walk-note">Hele populasjonen → del på \(n\). Det er delingstallet som skiller 1.7 fra 1.6.</div>`},
{chapter:"Kap 1", correct:"C",
 q:String.raw`Utvalgsvariansen er \(S_X^2=10\). <strong>Regn ut</strong> standardavviket \(S_X\) (formel 1.8).`,
 a:String.raw`5`, b:String.raw`100`, c:String.raw`3,16`, d:String.raw`2,83`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — 3,16.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Ta kvadratrota: \(\sqrt{10}\approx3{,}16\).</div></div><div class="walk-note">Tilbake til samme enhet som dataene.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`For \(n=7\) par har du \(\sum(X_i-\bar X)(Y_i-\bar Y)=24\). <strong>Regn ut</strong> kovariansen \(S_{XY}\) (formel 1.9).`,
 a:String.raw`4`, b:String.raw`3,43`, c:String.raw`24`, d:String.raw`6`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 4.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Summen av kryssproduktene er \(24\).</div><div class="proc-step"><strong>2 —</strong> Del på \(n-1=6\): \(\frac{24}{6}=4\).</div></div><div class="walk-note">Positivt → X og Y svinger sammen.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Du har \(S_{XY}=4\), \(S_X=2\) og \(S_Y=4\). <strong>Regn ut</strong> korrelasjonen \(R_{XY}\) (formel 1.10).`,
 a:String.raw`0,5`, b:String.raw`1`, c:String.raw`0,25`, d:String.raw`2`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 0,5.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> Gang standardavvikene: \(2\cdot4=8\).</div><div class="proc-step"><strong>2 —</strong> Del kovariansen på produktet: \(\frac{4}{8}=0{,}5\).</div></div><div class="walk-note">Moderat positiv lineær sammenheng; \(R\) ligger alltid mellom \(-1\) og \(1\).</div>`}
];
