// HSM126 — Gå formelen (regn det ut). Kapittel 10 (spesielle hypotesetester).
var QG10 = [
{chapter:"Kap 10", correct:"B",
 q:String.raw`To-utvalgs t-test. Fond 1: \(\sigma_1=25\%\), \(n_1=25\). <strong>Regn ut</strong> variansbidraget \(\frac{\sigma_1^2}{n_1}\) (formel 10.3).`,
 a:String.raw`0,25`, b:String.raw`0,0025`, c:String.raw`0,025`, d:String.raw`0,01`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 0,0025.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}25^2=0{,}0625\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}0625/25=0{,}0025\).</div></div><div class="walk-note">Første ledd under rota i standardfeilen.</div>`},
{chapter:"Kap 10", correct:"C",
 q:String.raw`Samme test. Fond 2: \(\sigma_2=10\%\), \(n_2=9\). <strong>Regn ut</strong> variansbidraget \(\frac{\sigma_2^2}{n_2}\).`,
 a:String.raw`0,011`, b:String.raw`0,10`, c:String.raw`≈ 0,0011`, d:String.raw`0,0009`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — ≈ 0,0011.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}10^2=0{,}01\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}01/9\approx0{,}00111\).</div></div><div class="walk-note">Andre ledd under rota.</div>`},
{chapter:"Kap 10", correct:"A",
 q:String.raw`De to bidragene er \(0{,}0025\) og \(0{,}00111\). <strong>Regn ut</strong> standardfeilen \(se=\sqrt{0{,}0025+0{,}00111}\).`,
 a:String.raw`≈ 0,060`, b:String.raw`0,00361`, c:String.raw`0,019`, d:String.raw`0,12`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,060.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}0025+0{,}00111=0{,}00361\).</div><div class="proc-step"><strong>2 —</strong> \(\sqrt{0{,}00361}\approx0{,}0601\).</div></div><div class="walk-note">Standardfeilen til forskjellen mellom fondene.</div>`},
{chapter:"Kap 10", correct:"D",
 q:String.raw`Snittforskjell \(0{,}22-0{,}08=0{,}14\), \(se\approx0{,}0601\). <strong>Regn ut</strong> testobservatoren \(t_{TS}=\frac{\bar X_1-\bar X_2}{se}\).`,
 a:String.raw`0,14`, b:String.raw`1,96`, c:String.raw`0,06`, d:String.raw`≈ 2,33`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D — ≈ 2,33.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}14/0{,}0601\approx2{,}33\).</div></div><div class="walk-note">Forskjellen er 2,33 standardfeil stor.</div>`},
{chapter:"Kap 10", correct:"B",
 q:String.raw`U-test for to andeler. Maskin A: 15 av 100. Maskin B: 2 av 60. <strong>Regn ut</strong> den samla andelen \(\hat p=\frac{x_1+x_2}{n_1+n_2}\) (formel 10.5).`,
 a:String.raw`0,15`, b:String.raw`≈ 0,106`, c:String.raw`0,085`, d:String.raw`0,033`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — ≈ 0,106.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(15+2=17\), \(100+60=160\).</div><div class="proc-step"><strong>2 —</strong> \(17/160\approx0{,}106\).</div></div><div class="walk-note">Under \(H_0\) er andelene like — derfor slår vi dem sammen.</div>`},
{chapter:"Kap 10", correct:"C",
 q:String.raw`Med \(\hat p\approx0{,}106\): <strong>regn ut</strong> standardfeilen \(se=\sqrt{\hat p(1-\hat p)\left(\frac{1}{100}+\frac{1}{60}\right)}\).`,
 a:String.raw`0,094`, b:String.raw`0,15`, c:String.raw`≈ 0,050`, d:String.raw`0,027`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — ≈ 0,050.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}106\cdot0{,}894\approx0{,}0949\).</div><div class="proc-step"><strong>2 —</strong> \(\frac{1}{100}+\frac{1}{60}\approx0{,}0267\).</div><div class="proc-step"><strong>3 —</strong> \(\sqrt{0{,}0949\cdot0{,}0267}\approx0{,}0503\).</div></div><div class="walk-note">Standardfeilen for differansen mellom andelene.</div>`},
{chapter:"Kap 10", correct:"A",
 q:String.raw`\(\hat p_1=0{,}15\), \(\hat p_2\approx0{,}033\), \(se\approx0{,}0503\). <strong>Regn ut</strong> \(z=\frac{\hat p_1-\hat p_2}{se}\).`,
 a:String.raw`≈ 2,32`, b:String.raw`0,117`, c:String.raw`1,96`, d:String.raw`0,05`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 2,32.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}15-0{,}033=0{,}117\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}117/0{,}0503\approx2{,}32\).</div></div><div class="walk-note">\(2{,}32>1{,}96\Rightarrow\) forkast lik defektandel (tosidet 5 %).</div>`},
{chapter:"Kap 10", correct:"D",
 q:String.raw`Kji-kvadrat. Kolonnesum \(F=91\), radsum Maskin A \(=100\), total \(=160\). <strong>Regn ut</strong> forventa antall \(E=\frac{\text{rad}\times\text{kolonne}}{\text{total}}\) (formel 10.7).`,
 a:String.raw`51`, b:String.raw`45,5`, c:String.raw`91`, d:String.raw`≈ 56,9`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D — ≈ 56,9.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(100\cdot91=9100\).</div><div class="proc-step"><strong>2 —</strong> \(9100/160\approx56{,}9\).</div></div><div class="walk-note">Hva cella skulle vært om maskin og kvalitet var uavhengige.</div>`},
{chapter:"Kap 10", correct:"A",
 q:String.raw`Defekt-cella for Maskin B: observert \(O=2\), forventa \(E=6{,}4\). <strong>Regn ut</strong> bidraget \(\frac{(O-E)^2}{E}\).`,
 a:String.raw`≈ 3,0`, b:String.raw`0,69`, c:String.raw`4,4`, d:String.raw`1,8`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 3,0.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(2-6{,}4=-4{,}4\).</div><div class="proc-step"><strong>2 —</strong> \((-4{,}4)^2=19{,}36\).</div><div class="proc-step"><strong>3 —</strong> \(19{,}36/6{,}4\approx3{,}0\).</div></div><div class="walk-note">Største enkeltbidrag — her sitter forskjellen.</div>`},
{chapter:"Kap 10", correct:"B",
 q:String.raw`Cellebidragene er \(0{,}61+0{,}07+1{,}80+1{,}01+0{,}12+3{,}00\). <strong>Regn ut</strong> \(\chi^2=\sum\frac{(O-E)^2}{E}\).`,
 a:String.raw`5,99`, b:String.raw`≈ 6,6`, c:String.raw`3,0`, d:String.raw`2,0`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — ≈ 6,6.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> summen \(\approx6{,}6\).</div><div class="proc-step"><strong>2 —</strong> \(df=(2-1)(3-1)=2\), kritisk \(\approx5{,}99\).</div><div class="proc-step"><strong>3 —</strong> \(6{,}6>5{,}99\Rightarrow\) forkast.</div></div><div class="walk-note">Fordelinga er ikke lik for de to maskinene.</div>`},
{chapter:"Kap 10", correct:"C",
 q:String.raw`Hele kjeden. Fond 1: \(\sigma_1=20\%\), \(n_1=16\). Fond 2: \(\sigma_2=8\%\), \(n_2=9\). <strong>Regn ut</strong> standardfeilen \(se=\sqrt{\frac{\sigma_1^2}{n_1}+\frac{\sigma_2^2}{n_2}}\).`,
 a:String.raw`0,0032`, b:String.raw`0,11`, c:String.raw`≈ 0,057`, d:String.raw`0,028`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — ≈ 0,057.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}20^2/16=0{,}0025\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}08^2/9\approx0{,}000711\).</div><div class="proc-step"><strong>3 —</strong> \(\sqrt{0{,}003211}\approx0{,}0567\).</div></div><div class="walk-note">Samler usikkerheten fra begge fond.</div>`},
{chapter:"Kap 10", correct:"A",
 q:String.raw`Snittforskjell \(0{,}18-0{,}05=0{,}13\), \(se\approx0{,}0567\). <strong>Regn ut</strong> \(t_{TS}\), og se mot \(t_{CV}\approx2{,}08\).`,
 a:String.raw`≈ 2,29`, b:String.raw`0,13`, c:String.raw`2,08`, d:String.raw`1,96`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 2,29.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}13/0{,}0567\approx2{,}29\).</div><div class="proc-step"><strong>2 —</strong> \(2{,}29>2{,}08\Rightarrow\) forkast \(H_0\).</div></div><div class="walk-note">Signifikant forskjell i avkastning.</div>`}
];
