// HSM126 — Gå formelen (regn det ut). Kapittel 11 (regresjonsanalyse).
var QG11 = [
{chapter:"Kap 11", correct:"A",
 q:String.raw`Multippel modell. elr-leddet har koeffisient \(-0{,}475\) og verdi \(20\). <strong>Regn ut</strong> leddet \(b\times X\) (formel 11.8).`,
 a:String.raw`−9,5`, b:String.raw`9,5`, c:String.raw`−0,475`, d:String.raw`−95`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — −9,5.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(-0{,}475\times20=-9{,}5\).</div></div><div class="walk-note">Negativt fortegn ⇒ leddet trekker Score ned.</div>`},
{chapter:"Kap 11", correct:"C",
 q:String.raw`int-leddet: koeffisient \(1{,}614\), verdi \(20\). <strong>Regn ut</strong> leddet.`,
 a:String.raw`1,614`, b:String.raw`16,14`, c:String.raw`≈ 32,28`, d:String.raw`3,228`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — ≈ 32,28.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1{,}614\times20=32{,}28\).</div></div><div class="walk-note">Inntekt drar mest opp av alle leddene.</div>`},
{chapter:"Kap 11", correct:"B",
 q:String.raw`spes-leddet: koeffisient \(-0{,}525\), verdi \(10\). <strong>Regn ut</strong> leddet.`,
 a:String.raw`5,25`, b:String.raw`−5,25`, c:String.raw`−0,525`, d:String.raw`−52,5`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — −5,25.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(-0{,}525\times10=-5{,}25\).</div></div><div class="walk-note">Hold fortegnet med — det er halve tolkninga.</div>`},
{chapter:"Kap 11", correct:"D",
 q:String.raw`eng-leddet: koeffisient \(-0{,}266\), verdi \(10\). <strong>Regn ut</strong> leddet.`,
 a:String.raw`2,66`, b:String.raw`−0,266`, c:String.raw`−26,6`, d:String.raw`−2,66`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D — −2,66.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(-0{,}266\times10=-2{,}66\).</div></div><div class="walk-note">Ett av de små negative bidragene.</div>`},
{chapter:"Kap 11", correct:"A",
 q:String.raw`Leddene er \(696{,}875\), \(-9{,}5\), \(+32{,}28\), \(-5{,}25\), \(-2{,}66\), \(-6{,}94\), \(-0{,}75\). <strong>Regn ut</strong> predikert \(\widehat{Score}\).`,
 a:String.raw`≈ 704`, b:String.raw`696,9`, c:String.raw`712`, d:String.raw`689`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 704.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(696{,}875-9{,}5+32{,}28-5{,}25-2{,}66-6{,}94-0{,}75\approx704{,}1\).</div></div><div class="walk-note">Modellens beste gjetning på Score for denne skolen.</div>`},
{chapter:"Kap 11", correct:"C",
 q:String.raw`Koeffisienten for int er \(\hat b=1{,}614\) med \(se=0{,}156\). <strong>Regn ut</strong> testobservatoren \(t_{TS}=\frac{\hat b-0}{se}\) (formel 11.2).`,
 a:String.raw`1,614`, b:String.raw`0,156`, c:String.raw`≈ 10,35`, d:String.raw`2,0`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — ≈ 10,35.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1{,}614-0=1{,}614\).</div><div class="proc-step"><strong>2 —</strong> \(1{,}614/0{,}156\approx10{,}35\).</div></div><div class="walk-note">Over ti standardfeil fra null ⇒ klart signifikant.</div>`},
{chapter:"Kap 11", correct:"B",
 q:String.raw`sppc-leddet: koeffisient \(-0{,}075\), verdi \(10\). <strong>Regn ut</strong> leddet.`,
 a:String.raw`0,75`, b:String.raw`−0,75`, c:String.raw`−0,075`, d:String.raw`−7,5`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — −0,75.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(-0{,}075\times10=-0{,}75\).</div></div><div class="walk-note">Minste bidraget i modellen.</div>`},
{chapter:"Kap 11", correct:"D",
 q:String.raw`lun-leddet: koeffisient \(-0{,}694\), verdi \(10\). <strong>Regn ut</strong> leddet.`,
 a:String.raw`6,94`, b:String.raw`−0,694`, c:String.raw`−69,4`, d:String.raw`−6,94`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D — −6,94.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(-0{,}694\times10=-6{,}94\).</div></div><div class="walk-note">Etter int er dette det nest største leddet i tallverdi.</div>`},
{chapter:"Kap 11", correct:"A",
 q:String.raw`En forklaringsvariabel har \(R_j^2=0{,}80\). <strong>Regn ut</strong> \(VIF=\frac{1}{1-R_j^2}\) (formel 11.12).`,
 a:String.raw`5`, b:String.raw`0,2`, c:String.raw`1,25`, d:String.raw`0,8`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 5.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1-0{,}80=0{,}20\).</div><div class="proc-step"><strong>2 —</strong> \(1/0{,}20=5\).</div></div><div class="walk-note">\(VIF=5\) ligger på grensa — over 5–10 er multikollinearitet et problem.</div>`}
];
