// HSM126 — Gå formelen (regn det ut). Kapittel 5.
// Fordeling: x=0,1,2,3 med P=0,1 / 0,3 / 0,4 / 0,2.
var QG5 = [
{chapter:"Kap 5", correct:"C",
 q:String.raw`Fordeling: \(x=0,1,2,3\) med \(P=0{,}1;\ 0{,}3;\ 0{,}4;\ 0{,}2\). <strong>Regn ut</strong> \(P(X=2)\) (formel 5.1).`,
 a:String.raw`0,2`, b:String.raw`0,3`, c:String.raw`0,4`, d:String.raw`0,8`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — 0,4.</strong> Punktsannsynlighet er ren avlesning.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> les av kolonnen \(x=2\): \(P(X=2)=0{,}4\).</div></div><div class="walk-note">«Nøyaktig» = ett tall, ingen summering.</div>`},
{chapter:"Kap 5", correct:"C",
 q:String.raw`Samme fordeling. <strong>Regn ut</strong> \(F(2)=P(X\le 2)\) (formel 5.2).`,
 a:String.raw`0,4`, b:String.raw`0,7`, c:String.raw`0,8`, d:String.raw`0,2`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — 0,8.</strong> Kumulativ = summer alt opp til grensa.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> ta radene \(x\le2\): \(0{,}1+0{,}3+0{,}4\).</div><div class="proc-step"><strong>2 —</strong> \(=0{,}8\).</div></div><div class="walk-note">80 % sjanse for 2 eller færre.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`Samme fordeling. <strong>Regn ut</strong> forventninga \(E[X]=\sum x\cdot P(X=x)\) (formel 5.3).`,
 a:String.raw`1,5`, b:String.raw`1,7`, c:String.raw`2,0`, d:String.raw`1,2`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 1,7.</strong> Vekt hver verdi med sannsynligheten.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0\cdot0{,}1+1\cdot0{,}3+2\cdot0{,}4+3\cdot0{,}2\).</div><div class="proc-step"><strong>2 —</strong> \(0+0{,}3+0{,}8+0{,}6=1{,}7\).</div></div><div class="walk-note">Tyngdepunktet — ikke det mest sannsynlige utfallet.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`Samme fordeling. <strong>Regn ut</strong> \(E[X^2]\) (formel 5.4, \(g(x)=x^2\)).`,
 a:String.raw`2,89`, b:String.raw`3,7`, c:String.raw`4,0`, d:String.raw`1,7`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 3,7.</strong> Kvadrer hver x før du vekter.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0\cdot0{,}1+1\cdot0{,}3+4\cdot0{,}4+9\cdot0{,}2\).</div><div class="proc-step"><strong>2 —</strong> \(0+0{,}3+1{,}6+1{,}8=3{,}7\).</div></div><div class="walk-note">Byggekloss til variansen.</div>`},
{chapter:"Kap 5", correct:"A",
 q:String.raw`Du har \(E[X]=1{,}7\) og \(E[X^2]=3{,}7\). <strong>Regn ut</strong> variansen (formel 5.5).`,
 a:String.raw`0,81`, b:String.raw`2,89`, c:String.raw`1,3`, d:String.raw`0,9`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 0,81.</strong> \(E[X^2]-(E[X])^2\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1{,}7^2=2{,}89\).</div><div class="proc-step"><strong>2 —</strong> \(3{,}7-2{,}89=0{,}81\).</div></div><div class="walk-note">Tallet er i kvadrert enhet.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`Du har \(\operatorname{Var}[X]=0{,}81\). <strong>Regn ut</strong> standardavviket (formel 5.6).`,
 a:String.raw`0,81`, b:String.raw`0,9`, c:String.raw`0,45`, d:String.raw`1,0`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 0,9.</strong> Ta kvadratrota.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{0{,}81}=0{,}9\).</div></div><div class="walk-note">Nå i samme enhet som X.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`En selger har \(E[X]=200\) salg. Bonus \(Y=2X+50\). <strong>Regn ut</strong> \(E[Y]\) (formel 5.7).`,
 a:String.raw`400`, b:String.raw`450`, c:String.raw`250`, d:String.raw`410`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 450.</strong> \(a+bE[X]\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(2\cdot200=400\).</div><div class="proc-step"><strong>2 —</strong> \(400+50=450\).</div></div><div class="walk-note">Både strekk og forskyvning følger med.</div>`},
{chapter:"Kap 5", correct:"C",
 q:String.raw`Leveringstid \(X\) har \(\operatorname{Var}[X]=16\). Ny tid \(Y=3X-4\). <strong>Regn ut</strong> \(\operatorname{Var}[Y]\) (formel 5.8).`,
 a:String.raw`48`, b:String.raw`96`, c:String.raw`144`, d:String.raw`432`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C — 144.</strong> \(b^2\operatorname{Var}[X]\); konstanten faller bort.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(3^2=9\).</div><div class="proc-step"><strong>2 —</strong> \(9\cdot16=144\).</div></div><div class="walk-note">\(-4\) flytter, sprer ikke.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`To uavhengige maskiner: \(\operatorname{Var}[X]=4\), \(\operatorname{Var}[Y]=9\). <strong>Regn ut</strong> \(\operatorname{Var}[X+Y]\) (formel 5.9).`,
 a:String.raw`5`, b:String.raw`13`, c:String.raw`36`, d:String.raw`6,5`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 13.</strong> Uavhengige varianser stables.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(4+9=13\).</div></div><div class="walk-note">Gjelder bare når de er uavhengige.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`Hele kjeden. Ny fordeling: \(x=0,1,2\) med \(P=0{,}5;\ 0{,}3;\ 0{,}2\). Gå 5.3→5.4→5.5→5.6 og <strong>regn ut</strong> standardavviket \(\sigma[X]\).`,
 a:String.raw`0,61`, b:String.raw`0,78`, c:String.raw`0,7`, d:String.raw`0,88`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — ≈ 0,78.</strong> Kjeden mater seg selv.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(E[X]=0{,}3+0{,}4=0{,}7\).</div><div class="proc-step"><strong>2 —</strong> \(E[X^2]=0{,}3+0{,}8=1{,}1\).</div><div class="proc-step"><strong>3 —</strong> \(\operatorname{Var}=1{,}1-0{,}49=0{,}61\).</div><div class="proc-step"><strong>4 —</strong> \(\sqrt{0{,}61}\approx0{,}78\).</div></div><div class="walk-note">5.4 mater 5.5 mater 5.6.</div>`}
];
