// HSM126 — Gå formelen (regn det ut). Kapittel 7 (sentrale fordelinger).
var QG7 = [
{chapter:"Kap 7", correct:"A",
 q:String.raw`\(n=10\) forsøk med tilbakelegging, \(p=0{,}3\). <strong>Regn ut</strong> \(P(X=4)\) binomisk (formel 7.1).`,
 a:String.raw`≈ 0,200`, b:String.raw`0,0081`, c:String.raw`0,117`, d:String.raw`0,300`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,200.</strong> \(\binom{n}{x}p^x(1-p)^{n-x}\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\binom{10}{4}=210\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}3^4=0{,}0081\), \(0{,}7^6\approx0{,}1176\).</div><div class="proc-step"><strong>3 —</strong> \(210\cdot0{,}0081\cdot0{,}1176\approx0{,}200\).</div></div><div class="walk-note">Koeffisient × to potenser.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`Eske: \(N=20\), \(M=8\) defekte, trekk \(n=5\) uten tilbakelegging. <strong>Regn ut</strong> \(P(X=2)\) hypergeometrisk (formel 7.2).`,
 a:String.raw`≈ 0,397`, b:String.raw`0,28`, c:String.raw`0,50`, d:String.raw`0,20`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,397.</strong> \(\frac{\binom{M}{x}\binom{N-M}{n-x}}{\binom{N}{n}}\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\binom{8}{2}=28\), \(\binom{12}{3}=220\).</div><div class="proc-step"><strong>2 —</strong> \(\binom{20}{5}=15\,504\).</div><div class="proc-step"><strong>3 —</strong> \(\frac{28\cdot220}{15\,504}\approx0{,}397\).</div></div><div class="walk-note">Uten tilbakelegging → hypergeometrisk.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`Kundesenter, \(\lambda=3\) samtaler per minutt. <strong>Regn ut</strong> \(P(X=5)\) Poisson (formel 7.3).`,
 a:String.raw`≈ 0,101`, b:String.raw`0,20`, c:String.raw`0,05`, d:String.raw`0,15`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,101.</strong> \(\frac{\lambda^x}{x!}e^{-\lambda}\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(3^5=243\), \(5!=120\) → \(2{,}025\).</div><div class="proc-step"><strong>2 —</strong> \(2{,}025\cdot e^{-3}\approx2{,}025\cdot0{,}0498\approx0{,}101\).</div></div><div class="walk-note">Én rate \(\lambda\) styrer alt.</div>`},
{chapter:"Kap 7", correct:"B",
 q:String.raw`Binomisk med \(n=50\), \(p=0{,}2\). <strong>Regn ut</strong> variansen \(\operatorname{Var}[X]=np(1-p)\).`,
 a:String.raw`10`, b:String.raw`8`, c:String.raw`2`, d:String.raw`40`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — 8.</strong> Ikke stopp på \(np\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(np=50\cdot0{,}2=10\) (forventninga).</div><div class="proc-step"><strong>2 —</strong> \(10\cdot0{,}8=8\).</div></div><div class="walk-note">Fella: \(np=10\) er snittet, ikke variansen.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`\(X\) normalfordelt, \(E[X]=100\), \(\sigma=15\). <strong>Regn ut</strong> z for verdien 120 (formel 7.8).`,
 a:String.raw`≈ 1,33`, b:String.raw`0,75`, c:String.raw`20`, d:String.raw`1,5`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 1,33.</strong> \(z=\frac{s-E[S]}{\sigma}\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(120-100=20\).</div><div class="proc-step"><strong>2 —</strong> \(20/15\approx1{,}33\).</div></div><div class="walk-note">1,33 standardavvik over snittet.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`Standardisert. <strong>Regn ut</strong> \(P(-1\le Z\le 1{,}5)\) med \(G(1{,}5)=0{,}933\), \(G(1)=0{,}841\) (formel 7.5).`,
 a:String.raw`≈ 0,774`, b:String.raw`0,933`, c:String.raw`0,159`, d:String.raw`0,50`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,774.</strong> \(G(b)-G(a)\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(G(-1)=1-0{,}841=0{,}159\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}933-0{,}159=0{,}774\).</div></div><div class="walk-note">\(G(-z)=1-G(z)\).</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`Binomisk \(n=40\), \(p=0{,}3\). <strong>Regn ut</strong> \(np(1-p)\) og avgjør om normaltilnærming er forsvarlig (formel 7.7).`,
 a:String.raw`8,4 — brukbar (≥5), ikke god (<10)`, b:String.raw`12 — god`, c:String.raw`5 — akkurat god`, d:String.raw`28 — brukbar`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 8,4.</strong> \(\ge5\) brukbar, \(<10\) ikke «god».</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(40\cdot0{,}3\cdot0{,}7=8{,}4\).</div></div><div class="walk-note">Vurder heltallskorreksjon.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`Tilnærming av binomisk \((n=40,p=0{,}3)\): \(E[S]=12\), \(\sigma=\sqrt{8{,}4}\approx2{,}90\). <strong>Regn ut</strong> z for \(P(X\le18)\) med heltallskorreksjon (formel 7.9).`,
 a:String.raw`≈ 2,24`, b:String.raw`2,07`, c:String.raw`6,5`, d:String.raw`1,96`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 2,24.</strong> \(z=\frac{s+0{,}5-E[S]}{\sigma}\).</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(18+0{,}5=18{,}5\).</div><div class="proc-step"><strong>2 —</strong> \(18{,}5-12=6{,}5\).</div><div class="proc-step"><strong>3 —</strong> \(6{,}5/2{,}90\approx2{,}24\).</div></div><div class="walk-note">\(+0{,}5\) tar med hele søyla.</div>`}
];
