// HSM126 — Gå formelen (regn det ut). Kapittel 8 (estimering).
var QG8 = [
{chapter:"Kap 8", correct:"A",
 q:String.raw`\(n=25\) målinger, \(\bar{X}=50\), \(S_X=10\). <strong>Regn ut</strong> standardfeilen \(\frac{S_X}{\sqrt{n}}\) (formel 8.4).`,
 a:String.raw`2`, b:String.raw`5`, c:String.raw`10`, d:String.raw`0,4`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — 2.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{25}=5\).</div><div class="proc-step"><strong>2 —</strong> \(10/5=2\).</div></div><div class="walk-note">Snittet er mer stabilt enn én måling.</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`Meningsmåling \(n=100\), \(\hat{p}=0{,}40\). <strong>Regn ut</strong> standardfeilen \(\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\) (formel 8.5).`,
 a:String.raw`≈ 0,049`, b:String.raw`0,24`, c:String.raw`0,0024`, d:String.raw`0,40`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,049.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}40\cdot0{,}60=0{,}24\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}24/100=0{,}0024\).</div><div class="proc-step"><strong>3 —</strong> \(\sqrt{0{,}0024}\approx0{,}049\).</div></div><div class="walk-note">Ingen 1,96 her — bare standardfeil.</div>`},
{chapter:"Kap 8", correct:"B",
 q:String.raw`\(n=64\), \(\bar{X}=100\), \(S_X=16\), 95 % KI (mange obs → z). <strong>Regn ut</strong> feilmarginen \(1{,}96\frac{S_X}{\sqrt{n}}\) (formel 8.9).`,
 a:String.raw`2`, b:String.raw`≈ 3,92`, c:String.raw`1,96`, d:String.raw`7,84`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B — ≈ 3,92.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{64}=8\), \(16/8=2\).</div><div class="proc-step"><strong>2 —</strong> \(1{,}96\cdot2=3{,}92\).</div></div><div class="walk-note">Intervall \(100\pm3{,}92\).</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`\(n=200\), \(\hat{p}=0{,}25\), 95 % KI for andel. <strong>Regn ut</strong> feilmarginen \(1{,}96\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\) (formel 8.8).`,
 a:String.raw`≈ 0,060`, b:String.raw`0,0306`, c:String.raw`0,030`, d:String.raw`0,12`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,060.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}25\cdot0{,}75=0{,}1875\); \(/200=0{,}0009375\).</div><div class="proc-step"><strong>2 —</strong> \(\sqrt{\ }\approx0{,}0306\).</div><div class="proc-step"><strong>3 —</strong> \(1{,}96\cdot0{,}0306\approx0{,}060\).</div></div><div class="walk-note">Som 8.5, men med 1,96 pålimt.</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`Lite utvalg \(n=10\), \(\bar{X}=20\), \(S_X=4\), \(t^{(9)}_{0{,}025}\approx2{,}262\). <strong>Regn ut</strong> feilmarginen for t-intervallet (formel 8.10).`,
 a:String.raw`≈ 2,86`, b:String.raw`2,53`, c:String.raw`1,96`, d:String.raw`3,92`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 2,86.</strong> Få obs → t, ikke z.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{10}\approx3{,}162\); \(4/3{,}162\approx1{,}265\).</div><div class="proc-step"><strong>2 —</strong> \(1{,}265\cdot2{,}262\approx2{,}86\).</div></div><div class="walk-note">t straffer den ekstra usikkerheten.</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`Trekk \(n=10\) uten tilbakelegging fra \(N=100\), \(\sigma^2=25\). <strong>Regn ut</strong> \(\operatorname{Var}[\bar{Y}]=\frac{N-n}{N-1}\cdot\frac{\sigma^2}{n}\) (formel 8.11).`,
 a:String.raw`≈ 2,27`, b:String.raw`2,5`, c:String.raw`0,909`, d:String.raw`22,7`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 2,27.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{90}{99}\approx0{,}909\).</div><div class="proc-step"><strong>2 —</strong> \(25/10=2{,}5\).</div><div class="proc-step"><strong>3 —</strong> \(0{,}909\cdot2{,}5\approx2{,}27\).</div></div><div class="walk-note">Endelig populasjon → mer presist snitt.</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`Hele kjeden. Lab: \(n=16\), \(\bar{X}=8{,}0\), \(S_X=1{,}2\), \(t^{(15)}_{0{,}025}\approx2{,}131\). <strong>Regn ut</strong> feilmarginen for 95 % t-intervall.`,
 a:String.raw`≈ 0,639`, b:String.raw`0,3`, c:String.raw`0,588`, d:String.raw`1,2`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A — ≈ 0,639.</strong> Valg z/t kom først: få obs → t.</div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{16}=4\); \(1{,}2/4=0{,}3\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}3\cdot2{,}131\approx0{,}639\).</div></div><div class="walk-note">Intervall \(8{,}0\pm0{,}64\).</div>`}
];
