// HSM126 — Kjenn formelen (gjenkjenning). Kapittel 1.
// Matte: \( ... \) (KaTeX). String.raw bevarer backslash.
var KJ1 = [
{chapter:"Kap 1", correct:"B",
 q:String.raw`Datasett (sortert): 3, 5, 5, 8, 10, 11, 14 (\(n=7\)). Du vil ha den <em>midterste</em> verdien som deler settet i to like halvdeler. Hvilken formel?`,
 a:String.raw`1.2 — \(Q_1=\text{obs. nr. }\frac{n+1}{4}\)`,
 b:String.raw`1.1 — \(\text{Median}=\text{obs. nr. }\frac{n+1}{2}\)`,
 c:String.raw`1.5 — \(\bar X=\frac{1}{n}\sum X_i\)`,
 d:String.raw`1.4 — modus`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «midterste», «to like halvdeler» → median. <strong>Svar: B (1.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> posisjon \(\frac{7+1}{2}=4\).</div><div class="proc-step"><strong>2 —</strong> 4. plass → <strong>8</strong>.</div></div><div class="walk-note">Medianen ser på rekkefølge, ikke ytterverdier.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Samme sett: 3, 5, 5, 8, 10, 11, 14 (\(n=7\)). Du vil ha <em>1. kvartil</em> — grensa for nederste fjerdedel. Hvilken formel?`,
 a:String.raw`1.2 — \(Q_1=\text{obs. nr. }\frac{n+1}{4}\)`,
 b:String.raw`1.1 — median`,
 c:String.raw`1.3 — \(Q_3=\text{obs. nr. }\frac{3(n+1)}{4}\)`,
 d:String.raw`1.5 — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «1. kvartil», «nederste fjerdedel» → nedre kvartil. <strong>Svar: A (1.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> posisjon \(\frac{7+1}{4}=2\).</div><div class="proc-step"><strong>2 —</strong> 2. plass → <strong>5</strong>.</div></div><div class="walk-note">En fjerdedel ligger på eller under.</div>`},
{chapter:"Kap 1", correct:"C",
 q:String.raw`Samme sett. Du vil ha <em>3. kvartil</em> — der øverste 25 % begynner. Hvilken formel?`,
 a:String.raw`1.1 — median`,
 b:String.raw`1.2 — \(Q_1=\text{obs. nr. }\frac{n+1}{4}\)`,
 c:String.raw`1.3 — \(Q_3=\text{obs. nr. }\frac{3(n+1)}{4}\)`,
 d:String.raw`1.4 — modus`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «3. kvartil», «øverste 25 %» → øvre kvartil. <strong>Svar: C (1.3).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> posisjon \(\frac{3(7+1)}{4}=6\).</div><div class="proc-step"><strong>2 —</strong> 6. plass → <strong>11</strong>.</div></div><div class="walk-note">Tre fjerdedeler under, øverste fjerdedel over.</div>`},
{chapter:"Kap 1", correct:"D",
 q:String.raw`I 3, 5, 5, 8, 10, 11, 14 — hvilken verdi forekommer <em>hyppigst</em>?`,
 a:String.raw`1.1 — median`,
 b:String.raw`1.5 — gjennomsnitt`,
 c:String.raw`1.2 — \(Q_1\)`,
 d:String.raw`1.4 — modus (verdien som forekommer hyppigst)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «hyppigst» → modus. <strong>Svar: D (1.4).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> 5 går igjen to ganger → modus = <strong>5</strong>.</div></div><div class="walk-note">Typetallet. Et sett kan ha flere.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Sett: 2, 4, 6, 8, 10 (\(n=5\)). Du vil ha <em>gjennomsnittet</em>. Hvilken formel?`,
 a:String.raw`1.1 — median`,
 b:String.raw`1.5 — \(\bar X=\frac{1}{n}\sum X_i\)`,
 c:String.raw`1.6 — \(S_X^2\)`,
 d:String.raw`1.8 — \(S_X=\sqrt{S_X^2}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «gjennomsnitt», «snitt» → \(\bar X\). <strong>Svar: B (1.5).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> sum \(=30\).</div><div class="proc-step"><strong>2 —</strong> \(\frac{30}{5}=6\).</div></div><div class="walk-note">Tyngdepunktet i dataene.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Sett 2, 4, 6, 8, 10 med \(\bar X=6\). Dette er et <em>utvalg</em>; du vil ha variansen. Hvilken formel?`,
 a:String.raw`1.6 — \(S_X^2=\frac{1}{n-1}\sum(X_i-\bar X)^2\)`,
 b:String.raw`1.7 — \(\sigma^2=\frac{1}{n}\sum(X_i-\bar X)^2\)`,
 c:String.raw`1.5 — \(\bar X\)`,
 d:String.raw`1.10 — \(R_{XY}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «utvalg» + «varians» → utvalgsvarians. <strong>Svar: A (1.6).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> avvik kvadrert: \(16,4,0,4,16\), sum \(40\).</div><div class="proc-step"><strong>2 —</strong> del på \(n-1=4\): \(10\).</div></div><div class="walk-note">Fella i B: deler på \(n\) (populasjon).</div>`},
{chapter:"Kap 1", correct:"C",
 q:String.raw`Samme tall, men nå er de <em>hele populasjonen</em>. Hvilken varians-formel?`,
 a:String.raw`1.6 — \(S_X^2=\frac{1}{n-1}\sum(X_i-\bar X)^2\)`,
 b:String.raw`1.8 — \(S_X\)`,
 c:String.raw`1.7 — \(\sigma^2=\frac{1}{n}\sum(X_i-\bar X)^2\)`,
 d:String.raw`1.5 — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «hele populasjonen» → populasjonsvarians. <strong>Svar: C (1.7).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> sum av kvadrerte avvik \(=40\).</div><div class="proc-step"><strong>2 —</strong> del på \(n=5\): \(8\).</div></div><div class="walk-note">Delingstallet (\(n\) vs \(n-1\)) skiller 1.7 fra 1.6.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Du har \(S_X^2=10\), men vil ha spredningen i <em>samme enhet</em> som dataene. Hvilken formel?`,
 a:String.raw`1.6 — \(S_X^2\)`,
 b:String.raw`1.8 — \(S_X=\sqrt{S_X^2}\)`,
 c:String.raw`1.5 — \(\bar X\)`,
 d:String.raw`1.7 — \(\sigma^2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «samme enhet» → standardavvik. <strong>Svar: B (1.8).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{10}\approx 3{,}16\).</div></div><div class="walk-note">Rota tar oss fra kvadrert enhet tilbake til dataenes skala.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`\(n=7\) par \((X,Y)\), og \(\sum(X_i-\bar X)(Y_i-\bar Y)=24\). Du vil vite om X og Y <em>svinger sammen</em>. Hvilken formel?`,
 a:String.raw`1.10 — \(R_{XY}=\frac{S_{XY}}{S_X S_Y}\)`,
 b:String.raw`1.9 — \(S_{XY}=\frac{1}{n-1}\sum(X_i-\bar X)(Y_i-\bar Y)\)`,
 c:String.raw`1.6 — \(S_X^2\)`,
 d:String.raw`1.5 — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «svinger sammen», to variabler → kovarians. <strong>Svar: B (1.9).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> kryssum \(=24\).</div><div class="proc-step"><strong>2 —</strong> del på \(n-1=6\): \(4\).</div></div><div class="walk-note">Positivt → høy X følges av høy Y. Enhetsavhengig — standardiseres i 1.10.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Du har \(S_{XY}=4\), \(S_X=2\), \(S_Y=4\). Du vil ha et <em>enhetsuavhengig</em> mål mellom \(-1\) og \(1\). Hvilken formel?`,
 a:String.raw`1.10 — \(R_{XY}=\frac{S_{XY}}{S_X\cdot S_Y}\)`,
 b:String.raw`1.9 — \(S_{XY}\)`,
 c:String.raw`1.8 — \(S_X\)`,
 d:String.raw`1.6 — \(S_X^2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «enhetsuavhengig», «mellom \(-1\) og \(1\)» → korrelasjon. <strong>Svar: A (1.10).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(S_X S_Y=8\).</div><div class="proc-step"><strong>2 —</strong> \(\frac{4}{8}=0{,}5\).</div></div><div class="walk-note">Moderat positiv lineær sammenheng.</div>`},
{chapter:"Kap 1", correct:"D",
 q:String.raw`<em>Mening.</em> \(R_{XY}=0{,}5\). Hva forteller det?`,
 a:String.raw`At X alltid er dobbelt så stor som Y`,
 b:String.raw`At halvparten av dataene mangler`,
 c:String.raw`At variablene er uavhengige`,
 d:String.raw`Moderat positiv lineær sammenheng — høy X følges typisk av høy Y, men ikke perfekt`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D.</strong> Korrelasjonen (1.10) gir retning og styrke. 0,5 = moderat positiv.</div><div class="walk-note">Nær \(+1\) sterk positiv, nær \(-1\) sterk negativ, nær 0 svak.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`<em>Hvorfor.</em> Hvorfor deler vi på \(n-1\) (ikke \(n\)) i <em>utvalgs</em>variansen (1.6)?`,
 a:String.raw`Fordi \(n-1\) alltid gir et mindre tall`,
 b:String.raw`Fordi én frihetsgrad er brukt på å anslå \(\bar X\) fra de samme dataene; \(n-1\) korrigerer for at utvalget ellers undervurderer spredningen`,
 c:String.raw`Fordi \(n-1\) er lettere å regne med`,
 d:String.raw`Fordi populasjonen alltid er én mindre`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Snittet er regnet fra utvalget selv, så avvikene blir litt for små; \(n-1\) blåser variansen opp passe til at estimatoren blir forventningsrett.</div><div class="walk-note">Ser du hele populasjonen (1.7), deler du på \(n\).</div>`}
];
