// HSM126 — Kjenn formelen (gjenkjenningstrening), Kapittel 1-5.
// Kilde: "Hør formelen — Gjenkjenningstrening Kap 1-5" (Notion).
// Matte skrives med \( ... \) (KaTeX). String.raw bevarer backslash.
var KJ1 = [
// ---------------- Kapittel 1 ----------------
{chapter:"Kap 1", correct:"B",
 q:String.raw`Du har datasettet (sortert): 3, 5, 5, 8, 10, 11, 14 — altså \(n=7\) observasjoner. Du vil finne den <em>midterste</em> verdien, den som deler datasettet i to like store halvdeler. Hvilken formel?`,
 a:String.raw`1.2 (2 steg) — \(Q_1=\text{obs. nr. }\frac{n+1}{4}\)`,
 b:String.raw`1.1 (2 steg) — \(\text{Median}=\text{obs. nr. }\frac{n+1}{2}\)`,
 c:String.raw`1.5 (2 steg) — \(\bar X=\frac{1}{n}\sum X_i\)`,
 d:String.raw`1.4 (1 steg) — modus`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «midterste verdien», «deler i to like halvdeler» → median-rommet. <strong>Svar: B — formel 1.1,</strong> \(\text{Median}=\text{obs. nr. }\frac{n+1}{2}\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> finn posisjonen: \(\frac{7+1}{2}=4\).</div><div class="proc-step"><strong>Steg 2 —</strong> les av 4. plass: 3, 5, 5, <strong>8</strong>, 10, 11, 14 → 8.</div></div><div class="walk-note">8 er midtpunktet — like mange under som over. Medianen bryr seg bare om rekkefølgen, ikke om hvor ekstreme ytterverdiene er.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Samme sorterte datasett: 3, 5, 5, 8, 10, 11, 14 (\(n=7\)). Du vil finne <em>1. kvartil</em> — verdien som skiller av den nederste fjerdedelen. Hvilken formel?`,
 a:String.raw`1.2 (2 steg) — \(Q_1=\text{obs. nr. }\frac{n+1}{4}\)`,
 b:String.raw`1.1 (2 steg) — \(\text{Median}=\text{obs. nr. }\frac{n+1}{2}\)`,
 c:String.raw`1.3 (2 steg) — \(Q_3=\text{obs. nr. }\frac{3(n+1)}{4}\)`,
 d:String.raw`1.5 (2 steg) — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «1. kvartil», «nederste fjerdedel» → kvartil-rommet (nedre). <strong>Svar: A — formel 1.2,</strong> \(Q_1=\text{obs. nr. }\frac{n+1}{4}\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> posisjonen: \(\frac{7+1}{4}=2\).</div><div class="proc-step"><strong>Steg 2 —</strong> les av 2. plass: 3, <strong>5</strong>, 5, 8, 10, 11, 14 → 5.</div></div><div class="walk-note">En fjerdedel av observasjonene ligger på eller under denne verdien.</div>`},
{chapter:"Kap 1", correct:"C",
 q:String.raw`Samme datasett. Du vil ha <em>3. kvartil</em> — verdien der de øverste 25 % begynner. Hvilken formel?`,
 a:String.raw`1.1 (2 steg) — median`,
 b:String.raw`1.2 (2 steg) — \(Q_1=\text{obs. nr. }\frac{n+1}{4}\)`,
 c:String.raw`1.3 (2 steg) — \(Q_3=\text{obs. nr. }\frac{3(n+1)}{4}\)`,
 d:String.raw`1.4 (1 steg) — modus`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «3. kvartil», «øverste 25 %» → kvartil-rommet (øvre). <strong>Svar: C — formel 1.3,</strong> \(Q_3=\text{obs. nr. }\frac{3(n+1)}{4}\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> posisjonen: \(\frac{3(7+1)}{4}=6\).</div><div class="proc-step"><strong>Steg 2 —</strong> les av 6. plass: 3, 5, 5, 8, 10, <strong>11</strong>, 14 → 11.</div></div><div class="walk-note">Tre fjerdedeler ligger under, den øverste fjerdedelen over.</div>`},
{chapter:"Kap 1", correct:"D",
 q:String.raw`I datasettet 3, 5, 5, 8, 10, 11, 14 — hvilken verdi forekommer <em>hyppigst</em>? Hvilket begrep?`,
 a:String.raw`1.1 (2 steg) — median`,
 b:String.raw`1.5 (2 steg) — gjennomsnitt`,
 c:String.raw`1.2 (2 steg) — \(Q_1\)`,
 d:String.raw`1.4 (1 steg) — modus (verdien som forekommer hyppigst)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «forekommer hyppigst» → modus. <strong>Svar: D — formel 1.4,</strong> modus.</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> tell forekomstene: 5 kommer to ganger, alle andre én gang → modus = 5.</div></div><div class="walk-note">Typetallet, det vanligste utfallet. Modus trenger ikke ligge i midten — og et datasett kan ha flere.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Nytt datasett: 2, 4, 6, 8, 10 (\(n=5\)). Du vil ha <em>gjennomsnittet</em> — snittverdien. Hvilken formel?`,
 a:String.raw`1.1 (2 steg) — median`,
 b:String.raw`1.5 (2 steg) — \(\bar X=\frac{1}{n}\sum X_i\)`,
 c:String.raw`1.6 (4 steg) — \(S_X^2\)`,
 d:String.raw`1.8 (1 steg) — \(S_X=\sqrt{S_X^2}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «gjennomsnitt», «snittverdi» → gjennomsnitts-rommet. <strong>Svar: B — formel 1.5,</strong> \(\bar X=\frac{1}{n}\sum X_i\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> summer alle: \(2+4+6+8+10=30\).</div><div class="proc-step"><strong>Steg 2 —</strong> del på n: \(\frac{30}{5}=6\).</div></div><div class="walk-note">Tyngdepunktet i dataene — balansepunktet om du la dem på en tallinje. fx-82CW: les \(\bar x\) i statistikkmodus.</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Samme datasett 2, 4, 6, 8, 10 med snitt \(\bar X=6\). Dette er et <em>utvalg</em>, og du vil ha variansen (spredningen). Hvilken formel?`,
 a:String.raw`1.6 (4 steg) — \(S_X^2=\frac{1}{n-1}\sum(X_i-\bar X)^2\)`,
 b:String.raw`1.7 (4 steg) — \(\sigma^2=\frac{1}{n}\sum(X_i-\bar X)^2\)`,
 c:String.raw`1.5 (2 steg) — \(\bar X\)`,
 d:String.raw`1.10 (2 steg) — \(R_{XY}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «utvalg», «varians» → utvalgsvarians-rommet. <strong>Svar: A — formel 1.6,</strong> \(S_X^2=\frac{1}{n-1}\sum(X_i-\bar X)^2\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> avvik fra snittet: \(-4,\ -2,\ 0,\ 2,\ 4\).</div><div class="proc-step"><strong>Steg 2 —</strong> kvadrer: \(16,\ 4,\ 0,\ 4,\ 16\).</div><div class="proc-step"><strong>Steg 3 —</strong> summer: \(40\).</div><div class="proc-step"><strong>Steg 4 —</strong> del på \(n-1=4\): \(\frac{40}{4}=10\).</div></div><div class="walk-note">Fella i B: deler du på \(n\) i stedet for \(n-1\), regner du <em>populasjons</em>varians.</div>`},
{chapter:"Kap 1", correct:"C",
 q:String.raw`Tenk deg nå at de fem tallene 2, 4, 6, 8, 10 er <em>hele populasjonen</em>, ikke et utvalg. Hvilken varians-formel gjelder da?`,
 a:String.raw`1.6 (4 steg) — \(S_X^2=\frac{1}{n-1}\sum(X_i-\bar X)^2\)`,
 b:String.raw`1.8 (1 steg) — \(S_X\)`,
 c:String.raw`1.7 (4 steg) — \(\sigma^2=\frac{1}{n}\sum(X_i-\bar X)^2\)`,
 d:String.raw`1.5 (2 steg) — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «hele populasjonen» → populasjonsvarians-rommet. <strong>Svar: C — formel 1.7,</strong> \(\sigma^2=\frac{1}{n}\sum(X_i-\bar X)^2\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> avvik: \(-4,\ -2,\ 0,\ 2,\ 4\); kvadrert: \(16,\ 4,\ 0,\ 4,\ 16\); sum \(40\).</div><div class="proc-step"><strong>Steg 2 —</strong> del på \(n=5\): \(\frac{40}{5}=8\).</div></div><div class="walk-note">Samme spredning, men delt på \(n\) fordi vi ser hele populasjonen. Delingstallet (\(n\) mot \(n-1\)) er det som skiller 1.7 fra 1.6.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Du har utvalgsvariansen \(S_X^2=10\), men vil ha spredningen i <em>samme enhet</em> som dataene. Hvilken formel?`,
 a:String.raw`1.6 (4 steg) — \(S_X^2\)`,
 b:String.raw`1.8 (1 steg) — \(S_X=\sqrt{S_X^2}\)`,
 c:String.raw`1.5 (2 steg) — \(\bar X\)`,
 d:String.raw`1.7 (4 steg) — \(\sigma^2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «samme enhet som dataene» → standardavvik-rommet. <strong>Svar: B — formel 1.8,</strong> \(S_X=\sqrt{S_X^2}\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> ta kvadratrota: \(\sqrt{10}\approx 3{,}16\).</div></div><div class="walk-note">Variansen var i kvadrert enhet; rota tar oss tilbake til dataenes egen skala.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`Du har \(n=7\) par \((X,Y)\) og har regnet ut \(\sum(X_i-\bar X)(Y_i-\bar Y)=24\). Du vil vite om X og Y <em>svinger sammen</em> — kovariansen. Hvilken formel?`,
 a:String.raw`1.10 (2 steg) — \(R_{XY}=\frac{S_{XY}}{S_X S_Y}\)`,
 b:String.raw`1.9 (2 steg) — \(S_{XY}=\frac{1}{n-1}\sum(X_i-\bar X)(Y_i-\bar Y)\)`,
 c:String.raw`1.6 (4 steg) — \(S_X^2\)`,
 d:String.raw`1.5 (2 steg) — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «svinger sammen», to variabler → kovarians-rommet. <strong>Svar: B — formel 1.9,</strong> \(S_{XY}=\frac{1}{n-1}\sum(X_i-\bar X)(Y_i-\bar Y)\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> du har summen av kryssproduktene: \(24\).</div><div class="proc-step"><strong>Steg 2 —</strong> del på \(n-1=6\): \(\frac{24}{6}=4\).</div></div><div class="walk-note">Positivt → når X ligger over snittet, ligger Y typisk også over. Størrelsen er enhetsavhengig, så vi standardiserer den ofte til en korrelasjon (1.10).</div>`},
{chapter:"Kap 1", correct:"A",
 q:String.raw`Du har kovariansen \(S_{XY}=4\) og standardavvikene \(S_X=2\) og \(S_Y=4\). Du vil ha et <em>enhetsuavhengig</em> mål på sammenhengen, mellom \(-1\) og \(1\). Hvilken formel?`,
 a:String.raw`1.10 (2 steg) — \(R_{XY}=\frac{S_{XY}}{S_X\cdot S_Y}\)`,
 b:String.raw`1.9 (2 steg) — \(S_{XY}\)`,
 c:String.raw`1.8 (1 steg) — \(S_X\)`,
 d:String.raw`1.6 (4 steg) — \(S_X^2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Ordet som avgjør:</strong> «enhetsuavhengig», «mellom \(-1\) og \(1\)» → korrelasjons-rommet. <strong>Svar: A — formel 1.10,</strong> \(R_{XY}=\frac{S_{XY}}{S_X\cdot S_Y}\).</div><div class="proc-block"><div class="proc-title">Steg for steg</div><div class="proc-step"><strong>Steg 1 —</strong> gang standardavvikene: \(2\cdot 4=8\).</div><div class="proc-step"><strong>Steg 2 —</strong> del kovariansen på produktet: \(\frac{4}{8}=0{,}5\).</div></div><div class="walk-note">Moderat positiv lineær sammenheng. Fordi vi deler bort enhetene, ligger R alltid mellom \(-1\) og \(1\).</div>`},
{chapter:"Kap 1", correct:"D",
 q:String.raw`<em>Betydnings-spørsmål.</em> Korrelasjonen \(R_{XY}\) kom ut til 0,5. Hva forteller det deg?`,
 a:String.raw`At X alltid er dobbelt så stor som Y`,
 b:String.raw`At halvparten av dataene mangler`,
 c:String.raw`At variablene er uavhengige`,
 d:String.raw`At det er en moderat positiv lineær sammenheng — høy X følges typisk av høy Y, men ikke perfekt`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D.</strong> Korrelasjonen (1.10) måler retning og styrke på den lineære sammenhengen. 0,5 er moderat positiv.</div><div class="walk-note">Ingen steg — ren mening. R nær \(+1\) = sterk positiv, nær \(-1\) = sterk negativ, nær 0 = svak. Fortegnet gir retning, tallverdien gir styrke.</div>`},
{chapter:"Kap 1", correct:"B",
 q:String.raw`<em>Hvorfor-spørsmål.</em> Hvorfor deler vi på \(n-1\) (ikke \(n\)) i <em>utvalgs</em>variansen (1.6)?`,
 a:String.raw`Fordi \(n-1\) alltid gir et mindre tall`,
 b:String.raw`Fordi vi har brukt opp én frihetsgrad på å anslå snittet \(\bar X\) fra de samme dataene, så delingen på \(n-1\) korrigerer for at utvalget ellers ville undervurdert spredningen`,
 c:String.raw`Fordi \(n-1\) er lettere å regne med`,
 d:String.raw`Fordi populasjonen alltid er én mindre`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Snittet er regnet fra utvalget selv, så avvikene blir litt for små; \(n-1\) blåser variansen opp akkurat passe til at estimatoren blir forventningsrett.</div><div class="walk-note">Ser du <em>hele</em> populasjonen (1.7), trenger du