// HSM126 — Kjenn formelen. Kapittel 10 (hypotesetester, oversikt).
var KJ10 = [
{chapter:"Kap 10", correct:"A",
 q:String.raw`Normalfordelt, \(n{=}15\), \(\bar X{=}22\), \(S_X{=}4\). Du tester snittet mot \(\mu_0{=}20\), \(\sigma\) ukjent. Hvilken testobservator?`,
 a:String.raw`10.2 — \(t=\frac{\bar X-\mu_0}{S_X/\sqrt n}\)`,
 b:String.raw`10.1 — \(z=\frac{\hat p-p_0}{\sqrt{p_0(1-p_0)/n}}\)`,
 c:String.raw`10.3 — \(t=\frac{\bar X_1-\bar X_2}{se}\)`,
 d:String.raw`10.6 — \(\chi^2=\sum\frac{(O-E)^2}{E}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «étt snitt, \(\sigma\) ukjent» → én-utvalgs t. <strong>Svar: A (10.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{22-20}{4/\sqrt{15}}\approx1{,}94\).</div></div><div class="walk-note">\(df=n-1=14\).</div>`},
{chapter:"Kap 10", correct:"C",
 q:String.raw`\(n{=}200\), \(\hat p{=}0{,}33\), test mot \(p_0{=}0{,}30\). Hvilken testobservator?`,
 a:String.raw`10.2 — \(t=\frac{\bar X-\mu_0}{S_X/\sqrt n}\)`,
 b:String.raw`10.5 — \(z=\frac{\hat p_1-\hat p_2}{se}\)`,
 c:String.raw`10.1 — \(z=\frac{\hat p-p_0}{\sqrt{p_0(1-p_0)/n}}\)`,
 d:String.raw`10.7 — \(\chi^2=\sum\frac{(O-E)^2}{E}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «én andel mot kjent \(p_0\)» → andels-z. <strong>Svar: C (10.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{0{,}33-0{,}30}{\sqrt{0{,}30{\cdot}0{,}70/200}}\approx0{,}93\).</div></div><div class="walk-note">Nevner bruker \(p_0\), ikke \(\hat p\).</div>`},
{chapter:"Kap 10", correct:"D",
 q:String.raw`To uavhengige grupper, snitt \(78\) og \(74\). Du vil teste om snittene er ulike. Hvilken testobservator?`,
 a:String.raw`10.2 — \(t=\frac{\bar X-\mu_0}{S_X/\sqrt n}\)`,
 b:String.raw`10.5 — \(z=\frac{\hat p_1-\hat p_2}{se}\)`,
 c:String.raw`10.4 — Wilcoxon rangtest`,
 d:String.raw`10.3 — \(t=\frac{\bar X_1-\bar X_2}{se}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «to snitt, sammenlign» → to-utvalgs t. <strong>Svar: D (10.3).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> f.eks. \(\frac{78-74}{\sqrt{36/30+25/25}}=\frac{4}{\sqrt{2{,}2}}\approx2{,}70\).</div></div><div class="walk-note">Teller = forskjell i snitt; nevner = samlet \(se\).</div>`},
{chapter:"Kap 10", correct:"B",
 q:String.raw`To grupper, andeler \(0{,}40\) og \(0{,}30\). Du vil teste om andelene er ulike. Hvilken testobservator?`,
 a:String.raw`10.1 — \(z=\frac{\hat p-p_0}{\sqrt{p_0(1-p_0)/n}}\)`,
 b:String.raw`10.5 — \(z=\frac{\hat p_1-\hat p_2}{se}\)`,
 c:String.raw`10.3 — \(t=\frac{\bar X_1-\bar X_2}{se}\)`,
 d:String.raw`10.7 — \(\chi^2=\sum\frac{(O-E)^2}{E}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «to andeler» → to-utvalgs andels-z. <strong>Svar: B (10.5).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> samlet \(\bar p\), så \(\frac{0{,}40-0{,}30}{se}\approx1{,}48\).</div></div><div class="walk-note">Bruk samlet (pooled) andel i \(se\).</div>`},
{chapter:"Kap 10", correct:"A",
 q:String.raw`Krysstabell: er to kategoriske variabler <em>uavhengige</em>? Hvilken test?`,
 a:String.raw`10.7 — \(\chi^2=\sum\frac{(O-E)^2}{E}\) (uavhengighet)`,
 b:String.raw`10.6 — \(\chi^2\) (tilpasning)`,
 c:String.raw`10.5 — \(z=\frac{\hat p_1-\hat p_2}{se}\)`,
 d:String.raw`10.3 — \(t=\frac{\bar X_1-\bar X_2}{se}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «krysstabell, uavhengighet» → kjikvadrat uavhengighet. <strong>Svar: A (10.7).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(E=\frac{\text{rad}{\cdot}\text{kol}}{\text{total}}\); \(df=(r-1)(k-1)\).</div></div><div class="walk-note">Tilpasning (10.6) tester én variabel mot en gitt fordeling.</div>`},
{chapter:"Kap 10", correct:"C",
 q:String.raw`En terning: stemmer de observerte hyppighetene med en <em>rettferdig</em> (uniform) fordeling? Hvilken test?`,
 a:String.raw`10.7 — \(\chi^2\) (uavhengighet)`,
 b:String.raw`10.1 — andels-z`,
 c:String.raw`10.6 — \(\chi^2=\sum\frac{(O-E)^2}{E}\) (tilpasning)`,
 d:String.raw`10.2 — én-utvalgs t`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «én variabel mot en forventet fordeling» → tilpasning. <strong>Svar: C (10.6).</strong></div><div class="walk-note">\(E\) kommer fra modellen (her: total/6).</div>`},
{chapter:"Kap 10", correct:"B",
 q:String.raw`Små utvalg, data klart <em>ikke</em> normalfordelte, du vil sammenligne to grupper på median. Hvilken test?`,
 a:String.raw`10.2 — én-utvalgs t`,
 b:String.raw`10.4 — Wilcoxon rangtest`,
 c:String.raw`10.3 — to-utvalgs t`,
 d:String.raw`10.6 — \(\chi^2\) (tilpasning)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «ikke-normalt, rangbasert» → ikke-parametrisk. <strong>Svar: B (10.4).</strong></div><div class="walk-note">Bytter råverdier mot ranger — robust mot uteliggere.</div>`},
{chapter:"Kap 10", correct:"D",
 q:String.raw`Du vil ha selve <em>rekkefølgen</em> på stegene i en hypotesetest (sett opp \(H_0/H_1\), velg test, regn, konkluder). Hvilket punkt?`,
 a:String.raw`9.1 — elementene i en test`,
 b:String.raw`10.6 — \(\chi^2\) (tilpasning)`,
 c:String.raw`9.8 — testobservator`,
 d:String.raw`10.8 — stegene i praksis`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «rekkefølge/oppskrift» → 10.8. <strong>Svar: D.</strong></div><div class="walk-note">9.1 lister delene; 10.8 er gjennomføringen.</div>`},
{chapter:"Kap 10", correct:"C",
 q:String.raw`<em>Mening.</em> \(t_{TS}{=}2{,}70\), kritisk verdi \(2{,}05\) (tosidet). Hva gjør du?`,
 a:String.raw`Beholder \(H_0\)`,
 b:String.raw`Kan ikke avgjøre`,
 c:String.raw`Forkaster \(H_0\): observatoren er forbi kritisk verdi`,
 d:String.raw`Øker \(\alpha\)`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> \(|t_{TS}|>\) kritisk → inn i forkastningsområdet → forkast.</div><div class="walk-note">Samme konklusjon som \(P<\alpha\).</div>`},
{chapter:"Kap 10", correct:"A",
 q:String.raw`<em>Hvorfor.</em> Hvorfor bytte til rangtest (10.4) i stedet for t når data ikke er normale?`,
 a:String.raw`t hviler på normalitet; ranger gjør testen robust mot skjevhet og uteliggere`,
 b:String.raw`Rangtest gir alltid lavere P-verdi`,
 c:String.raw`t finnes ikke for små utvalg`,
 d:String.raw`Ranger krever normalfordeling`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> Bryter forutsetningen for t, faller rangbaserte tester tilbake på rekkefølge — langt mindre følsomme for haler.</div><div class="walk-note">Prisen er litt lavere styrke når data faktisk er normale.</div>`},
{chapter:"Kap 10", correct:"B",
 q:String.raw`<em>Hvorfor.</em> Hvorfor kvadrere \((O-E)\) og dele på \(E\) i kjikvadrat?`,
 a:String.raw`For å gjøre tallet penere`,
 b:String.raw`Kvadrering hindrer at avvik kanselerer; deling på \(E\) veier avvik mot forventet størrelse`,
 c:String.raw`Fordi \(O\) alltid er større enn \(E\)`,
 d:String.raw`For å gjøre testen ensidet`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Uten kvadrering ville positive og negative avvik nulle hverandre; \(/E\) gjør et avvik på 5 viktigere når \(E\) er liten.</div><div class="walk-note">Derfor er \(\chi^2\ge0\) og bare øvre hale teller.</div>`}
];
