// HSM126 — Kjenn formelen. Kapittel 11 (regresjonsanalyse).
var KJ11 = [
{chapter:"Kap 11", correct:"A",
 q:String.raw`Én forklaringsvariabel, du antar en rett linje med støyledd. Hvilken modell?`,
 a:String.raw`11.1 — \(Y_j=b_0+b_1X_j+\varepsilon_j\)`,
 b:String.raw`11.8 — multippel: \(Y=b_0+b_1X_1+\dots+b_kX_k\)`,
 c:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 d:String.raw`11.2 — \(t=\frac{\hat b_1-\beta_1}{se(\hat b_1)}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «én X, rett linje» → enkel lineær regresjon. <strong>Svar: A (11.1).</strong></div><div class="walk-note">Flere X-er → 11.8 (multippel).</div>`},
{chapter:"Kap 11", correct:"C",
 q:String.raw`\(\hat b_1{=}2{,}5\), \(se(\hat b_1){=}0{,}8\). Du vil teste om stigningstallet er forskjellig fra 0. Hvilken formel?`,
 a:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 b:String.raw`11.3 — \(df=n-2\)`,
 c:String.raw`11.2 — \(t=\frac{\hat b_1-\beta_1}{se(\hat b_1)}\)`,
 d:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «test av étt stigningstall» → t-test. <strong>Svar: C (11.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{2{,}5-0}{0{,}8}\approx3{,}13\).</div></div><div class="walk-note">\(df=n-2\) i enkel regresjon.</div>`},
{chapter:"Kap 11", correct:"D",
 q:String.raw`Enkel regresjon med \(n{=}12\). Du vil ha frihetsgradene for t-testen av stigningstallet. Hvilken formel?`,
 a:String.raw`11.9 — \(df=n-k-1\)`,
 b:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 c:String.raw`11.2 — \(t=\frac{\hat b_1-\beta_1}{se}\)`,
 d:String.raw`11.3 — \(df=n-2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «enkel regresjon, df» → 11.3. <strong>Svar: D.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(12-2=10\).</div></div><div class="walk-note">Multippel bruker \(n-k-1\) (11.9).</div>`},
{chapter:"Kap 11", correct:"B",
 q:String.raw`\(\sum(y_i-\hat y_i)^2{=}90\), \(n{=}12\). Du vil ha typisk avstand fra punktene til linja (residualstandardavvik). Hvilken formel?`,
 a:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 b:String.raw`11.4 — \(RSE=\sqrt{\frac{\sum(y_i-\hat y_i)^2}{n-2}}\)`,
 c:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 d:String.raw`11.2 — \(t=\frac{\hat b_1-\beta_1}{se}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «typisk residual» → RSE. <strong>Svar: B (11.4).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{\frac{90}{10}}=3\).</div></div><div class="walk-note">Spredning rundt linja, i \(Y\)-enheter.</div>`},
{chapter:"Kap 11", correct:"A",
 q:String.raw`\(MSR{=}90\), \(MSE{=}9\). Du vil teste om modellen som helhet forklarer noe. Hvilken formel?`,
 a:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 b:String.raw`11.4 — \(RSE\)`,
 c:String.raw`11.3 — \(df=n-2\)`,
 d:String.raw`11.11 — justert \(R^2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «hele modellen» → F-test. <strong>Svar: A (11.5).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{90}{9}=10\).</div></div><div class="walk-note">Forklart variasjon delt på uforklart.</div>`},
{chapter:"Kap 11", correct:"C",
 q:String.raw`\(SST{=}180\), \(SSE{=}90\). Du vil ha andelen forklart variasjon. Hvilken formel?`,
 a:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 b:String.raw`11.4 — \(RSE\)`,
 c:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 d:String.raw`11.2 — \(t=\frac{\hat b_1-\beta_1}{se}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «andel forklart» → \(R^2\). <strong>Svar: C (11.7).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1-\frac{90}{180}=0{,}5\).</div></div><div class="walk-note">\(R^2\) ligger mellom 0 og 1.</div>`},
{chapter:"Kap 11", correct:"D",
 q:String.raw`<em>Mening.</em> \(\hat b_1{=}2{,}5\). Hva betyr det?`,
 a:String.raw`\(Y\) er 2,5 når \(X{=}0\)`,
 b:String.raw`Korrelasjonen er 2,5`,
 c:String.raw`Modellen forklarer 250%`,
 d:String.raw`\(Y\) øker med 2,5 enheter når \(X\) øker med 1`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D.</strong> Stigningstallet = endring i \(Y\) per enhets økning i \(X\). Konstantleddet \(b_0\) er verdien ved \(X{=}0\).</div><div class="walk-note">A forveksler stigningstall med konstantledd.</div>`},
{chapter:"Kap 11", correct:"B",
 q:String.raw`Tre forklaringsvariabler skal forutsi \(Y\). Hvilken modell?`,
 a:String.raw`11.1 — \(Y=b_0+b_1X+\varepsilon\)`,
 b:String.raw`11.8 — \(Y=b_0+b_1X_1+b_2X_2+b_3X_3+\varepsilon\)`,
 c:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 d:String.raw`11.12 — \(VIF_j=\frac{1}{1-R_j^2}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «flere X-er» → multippel regresjon. <strong>Svar: B (11.8).</strong></div><div class="walk-note">Hver \(b_i\) = effekt av \(X_i\) når de andre holdes fast.</div>`},
{chapter:"Kap 11", correct:"A",
 q:String.raw`Multippel regresjon, \(n{=}30\), \(k{=}3\) forklaringsvariabler. Du vil ha frihetsgradene for residualene. Hvilken formel?`,
 a:String.raw`11.9 — \(df=n-k-1\)`,
 b:String.raw`11.3 — \(df=n-2\)`,
 c:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 d:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «multippel, df» → 11.9. <strong>Svar: A.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(30-3-1=26\).</div></div><div class="walk-note">Hver ekstra X koster én frihetsgrad.</div>`},
{chapter:"Kap 11", correct:"C",
 q:String.raw`Multippel modell, forklart \(=120\) (\(k{=}3\)), uforklart \(=80\) (\(n{=}30\)). Du vil teste hele modellen. Hvilken formel?`,
 a:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 b:String.raw`11.2 — \(t=\frac{\hat b_1-\beta_1}{se}\)`,
 c:String.raw`11.10 — \(F=\frac{\text{forklart}/k}{\text{uforklart}/(n-k-1)}\)`,
 d:String.raw`11.3 — \(df=n-2\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «hele den multiple modellen» → 11.10. <strong>Svar: C.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{120/3}{80/26}\approx13{,}0\).</div></div><div class="walk-note">F med \(df_1=k\), \(df_2=n-k-1\).</div>`},
{chapter:"Kap 11", correct:"A",
 q:String.raw`\(R^2{=}0{,}60\), \(n{=}30\), \(k{=}3\). Du vil ha et mål som straffer for antall variabler. Hvilken formel?`,
 a:String.raw`11.11 — \(1-\frac{(1-R^2)(n-1)}{n-k-1}\)`,
 b:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 c:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 d:String.raw`11.12 — \(VIF_j=\frac{1}{1-R_j^2}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «straff for antall X-er» → justert \(R^2\). <strong>Svar: A (11.11).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1-\frac{0{,}40{\cdot}29}{26}\approx0{,}554\).</div></div><div class="walk-note">Justert \(R^2\le R^2\) alltid.</div>`},
{chapter:"Kap 11", correct:"D",
 q:String.raw`\(X_j\) regresseres mot de andre forklaringsvariablene og gir \(R_j^2{=}0{,}80\). Du vil måle multikolinearitet. Hvilken formel?`,
 a:String.raw`11.7 — \(R^2=1-\frac{SSE}{SST}\)`,
 b:String.raw`11.5 — \(F=\frac{MSR}{MSE}\)`,
 c:String.raw`11.11 — justert \(R^2\)`,
 d:String.raw`11.12 — \(VIF_j=\frac{1}{1-R_j^2}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «multikolinearitet» → VIF. <strong>Svar: D (11.12).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{1}{1-0{,}80}=5\).</div></div><div class="walk-note">\(VIF>5\)–10 = bekymringsverdig.</div>`},
{chapter:"Kap 11", correct:"B",
 q:String.raw`<em>Hvorfor.</em> Hvorfor bruke justert \(R^2\) i stedet for vanlig \(R^2\) i multippel regresjon?`,
 a:String.raw`Justert \(R^2\) er alltid større`,
 b:String.raw`Vanlig \(R^2\) stiger uansett når du legger til variabler; justert straffer unødvendige`,
 c:String.raw`Justert \(R^2\) krever normalfordeling`,
 d:String.raw`De er alltid like`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> \(R^2\) kan aldri synke når en X legges til, så den belønner overfitting. Justert \(R^2\) faller hvis variabelen ikke betaler for seg.</div><div class="walk-note">Derfor sammenligner man modeller på justert \(R^2\).</div>`},
{chapter:"Kap 11", correct:"C",
 q:String.raw`<em>Hvorfor.</em> Hvorfor er høy VIF et problem?`,
 a:String.raw`Den senker \(R^2\)`,
 b:String.raw`Den gjør \(Y\) ikke-normal`,
 c:String.raw`Variablene overlapper, så \(se\) til koeffisientene blåses opp og enkelteffekter blir ustabile`,
 d:String.raw`Den øker antall frihetsgrader`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> Når X-er er sterkt korrelerte, klarer ikke modellen å skille effektene — koeffisientene svinger vilt fra utvalg til utvalg.</div><div class="walk-note">Selve prediksjonen kan likevel være grei; det er <em>tolkningen</em> som lider.</div>`}
];
