// HSM126 — Kjenn formelen. Kapittel 2 (sannsynlighet).
var KJ2 = [
{chapter:"Kap 2", correct:"B",
 q:String.raw`En modell gir \(p_1=0{,}2,\ p_2=0{,}5,\ p_3=0{,}3\) for tre utfall. Hvilket krav avgjør om dette er en <em>gyldig</em> sannsynlighetsmodell?`,
 a:String.raw`2.5 — \(P(A^c)=1-P(A)\)`,
 b:String.raw`2.4 — \(0\le p_i\le 1\) og \(\sum p_i=1\)`,
 c:String.raw`2.6 — \(P(A\cup B)\)`,
 d:String.raw`2.1 — utfallsrom`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «gyldig modell» → modellkravet. <strong>Svar: B (2.4).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> hver \(p_i\) ligger i \([0,1]\). OK.</div><div class="proc-step"><strong>2 —</strong> \(0{,}2+0{,}5+0{,}3=1\). OK → gyldig.</div></div><div class="walk-note">To krav: ikke-negative, og summen \(=1\).</div>`},
{chapter:"Kap 2", correct:"C",
 q:String.raw`\(P(\text{regn})=0{,}7\). Hva er sannsynligheten for at det <em>ikke</em> regner?`,
 a:String.raw`2.6 — \(P(A\cup B)\)`,
 b:String.raw`2.4 — modellkravet`,
 c:String.raw`2.5 — \(P(A^c)=1-P(A)\)`,
 d:String.raw`2.7 — addisjon (tre)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «ikke» → komplement. <strong>Svar: C (2.5).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1-0{,}7=0{,}3\).</div></div><div class="walk-note">«Ikke» / «minst én» er ofte signal om komplement.</div>`},
{chapter:"Kap 2", correct:"A",
 q:String.raw`\(P(A)=0{,}5,\ P(B)=0{,}4,\ P(A\cap B)=0{,}2\). Du vil ha \(P(A\text{ eller }B)\) — minst én skjer. Hvilken formel?`,
 a:String.raw`2.6 — \(P(A\cup B)=P(A)+P(B)-P(A\cap B)\)`,
 b:String.raw`2.5 — komplement`,
 c:String.raw`2.7 — addisjon (tre)`,
 d:String.raw`2.4 — modellkravet`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «eller» / «minst én», to begivenheter med overlapp → addisjon (to). <strong>Svar: A (2.6).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}5+0{,}4=0{,}9\).</div><div class="proc-step"><strong>2 —</strong> trekk fra overlappet: \(0{,}9-0{,}2=0{,}7\).</div></div><div class="walk-note">Overlappet telles ellers to ganger.</div>`},
{chapter:"Kap 2", correct:"D",
 q:String.raw`A og B kan <em>ikke skje samtidig</em> (disjunkte), \(P(A)=0{,}3,\ P(B)=0{,}45\). Hva er \(P(A\cup B)\)?`,
 a:String.raw`2.5 — komplement`,
 b:String.raw`2.1 — utfallsrom`,
 c:String.raw`2.7 — addisjon (tre)`,
 d:String.raw`2.6 — \(P(A\cup B)=P(A)+P(B)-P(A\cap B)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «eller», men disjunkte → fortsatt 2.6, med \(P(A\cap B)=0\). <strong>Svar: D (2.6).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> disjunkt → \(P(A\cap B)=0\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}3+0{,}45-0=0{,}75\).</div></div><div class="walk-note">Disjunkt er bare spesialtilfellet der overlappet er null.</div>`},
{chapter:"Kap 2", correct:"B",
 q:String.raw`\(P(A)=P(B)=P(C)=0{,}3\); parvise snitt \(=0{,}1\); \(P(A\cap B\cap C)=0{,}05\). Du vil ha \(P(A\cup B\cup C)\). Hvilken formel?`,
 a:String.raw`2.6 — addisjon (to)`,
 b:String.raw`2.7 — \(P(A\cup B\cup C)=\sum P-\sum P(\text{par})+P(A\cap B\cap C)\)`,
 c:String.raw`2.5 — komplement`,
 d:String.raw`2.4 — modellkravet`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «tre begivenheter» i union → addisjon (tre). <strong>Svar: B (2.7).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> enkle: \(3\cdot 0{,}3=0{,}9\).</div><div class="proc-step"><strong>2 —</strong> minus par: \(0{,}9-3\cdot 0{,}1=0{,}6\).</div><div class="proc-step"><strong>3 —</strong> pluss trippel: \(0{,}6+0{,}05=0{,}65\).</div></div><div class="walk-note">Inklusjon–eksklusjon: trekk fra par, legg trippelen tilbake.</div>`},
{chapter:"Kap 2", correct:"C",
 q:String.raw`<em>Mening.</em> Hva er forskjellen på utfallsrommet (2.1) og en begivenhet (2.2)?`,
 a:String.raw`De er det samme`,
 b:String.raw`En begivenhet er alltid større enn utfallsrommet`,
 c:String.raw`Utfallsrommet \(\Omega\) er mengden av alle mulige utfall; en begivenhet er en delmengde av det`,
 d:String.raw`Utfallsrommet inneholder bare ett utfall`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> \(\Omega\) = alt som kan skje; en begivenhet = et utvalg av disse utfallene.</div><div class="walk-note">Sannsynlighet = begivenhetens «størrelse» delt på \(\Omega\).</div>`},
{chapter:"Kap 2", correct:"A",
 q:String.raw`<em>Hvorfor.</em> Hvorfor trekker vi fra \(P(A\cap B)\) i addisjonssetningen (2.6)?`,
 a:String.raw`Fordi utfallene i både A og B ellers ville blitt talt to ganger`,
 b:String.raw`For å gjøre svaret mindre`,
 c:String.raw`Fordi A og B alltid er disjunkte`,
 d:String.raw`Fordi sannsynligheter aldri kan summeres`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> \(P(A)\) og \(P(B)\) inneholder begge overlappet; én kopi må trekkes bort.</div><div class="walk-note">Disjunkt → overlapp \(=0\) → ingenting å trekke fra.</div>`}
];
