// HSM126 — Kjenn formelen. Kapittel 3 (kombinatorikk).
var KJ3 = [
{chapter:"Kap 3", correct:"B",
 q:String.raw`En PIN har 4 sifre (0–9), og sifre <em>kan gjentas</em>. Hvor mange koder? (Rekkefølge teller, med tilbakelegging.)`,
 a:String.raw`3.2 — \((N)_s=\frac{N!}{(N-s)!}\)`,
 b:String.raw`3.1 — \(N^s\)`,
 c:String.raw`3.3 — \(\binom{N}{s}\)`,
 d:String.raw`1.5 — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «kan gjentas» + rekkefølge teller → med tilbakelegging. <strong>Svar: B (3.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(N=10,\ s=4\).</div><div class="proc-step"><strong>2 —</strong> \(10^4=10\,000\).</div></div><div class="walk-note">Hvert valg har alle \(N\) muligheter fordi vi legger tilbake.</div>`},
{chapter:"Kap 3", correct:"A",
 q:String.raw`8 deltakere. Hvor mange måter kan gull, sølv, bronse fordeles? (Rekkefølge teller, <em>ingen gjentakelse</em>.)`,
 a:String.raw`3.2 — \((N)_s=\frac{N!}{(N-s)!}\)`,
 b:String.raw`3.1 — \(N^s\)`,
 c:String.raw`3.3 — \(\binom{N}{s}\)`,
 d:String.raw`2.6 — \(P(A\cup B)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> rekkefølge teller + uten tilbakelegging → ordnet utvalg. <strong>Svar: A (3.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(N=8,\ s=3\).</div><div class="proc-step"><strong>2 —</strong> \(8\cdot 7\cdot 6=336\).</div></div><div class="walk-note">Fallende produkt: én mindre å velge mellom for hver plass.</div>`},
{chapter:"Kap 3", correct:"B",
 q:String.raw`Velg en komité på 3 av 8. <em>Rekkefølge spiller ingen rolle.</em> Hvor mange komitéer?`,
 a:String.raw`3.1 — \(N^s\)`,
 b:String.raw`3.3 — \(\binom{N}{s}=\frac{N!}{s!(N-s)!}\)`,
 c:String.raw`3.2 — \((N)_s=\frac{N!}{(N-s)!}\)`,
 d:String.raw`2.5 — komplement`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «rekkefølge spiller ingen rolle» → uordnet utvalg. <strong>Svar: B (3.3).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> ordnet \(8\cdot 7\cdot 6=336\).</div><div class="proc-step"><strong>2 —</strong> del på \(3!=6\): \(\frac{336}{6}=56\).</div></div><div class="walk-note">Deling på \(s!\) fjerner de like utvalgene i ulik rekkefølge.</div>`},
{chapter:"Kap 3", correct:"A",
 q:String.raw`<em>Mening.</em> Når deler du ekstra på \(s!\) (går fra 3.2 til 3.3)?`,
 a:String.raw`Når rekkefølgen ikke spiller noen rolle — da er ordningene innen samme utvalg overflødige`,
 b:String.raw`Aldri — 3.2 og 3.3 gir alltid samme svar`,
 c:String.raw`Bare når \(N\) er et partall`,
 d:String.raw`Når du legger tilbake mellom trekkene`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> \(s!\) er antallet måter å ordne de samme \(s\) valgte på; bryr du deg ikke om rekkefølge, deler du dem bort.</div><div class="walk-note">Rekkefølge teller → 3.2. Rekkefølge irrelevant → 3.3.</div>`},
{chapter:"Kap 3", correct:"B",
 q:String.raw`<em>Mening.</em> Hva skiller 3.1 (\(N^s\)) fra 3.2 og 3.3?`,
 a:String.raw`3.1 gjelder bare partall`,
 b:String.raw`I 3.1 legger vi tilbake mellom trekkene, så hvert valg har \(N\) muligheter; 3.2 og 3.3 trekker uten tilbakelegging`,
 c:String.raw`3.1 gir alltid færre utfall`,
 d:String.raw`Det er ingen forskjell`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Tilbakelegging er skillet: med (3.1) eller uten (3.2/3.3).</div><div class="walk-note">«Kan gjentas» → 3.1. «Ingen gjentakelse» → 3.2/3.3.</div>`},
{chapter:"Kap 3", correct:"A",
 q:String.raw`<em>Hvorfor.</em> Hvorfor blir \((N)_s=\frac{N!}{(N-s)!}\) til det fallende produktet \(N(N-1)\cdots\)?`,
 a:String.raw`Fordi \((N-s)!\) kansellerer halen av \(N!\) og lar bare de \(s\) øverste faktorene stå igjen`,
 b:String.raw`Fordi fakultet alltid blir mindre`,
 c:String.raw`Fordi vi legger tilbake mellom trekkene`,
 d:String.raw`Fordi \(s\) alltid er større enn \(N\)`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> \(\frac{N!}{(N-s)!}\) stryker faktorene fra \((N-s)\) og ned, igjen står \(N(N-1)\cdots(N-s+1)\).</div><div class="walk-note">Akkurat de \(s\) valgene vi faktisk gjør.</div>`}
];
