// HSM126 — Kjenn formelen. Kapittel 4 (betinget sannsynlighet).
var KJ4 = [
{chapter:"Kap 4", correct:"B",
 q:String.raw`I en klasse er \(P(\text{jente}\cap\text{briller})=0{,}2\) og \(P(\text{jente})=0{,}5\). Du vil ha \(P(\text{briller}\mid\text{jente})\). Hvilken formel?`,
 a:String.raw`4.2 — Bayes`,
 b:String.raw`4.1 — \(P(A\mid B)=\frac{P(A\cap B)}{P(B)}\)`,
 c:String.raw`4.3 — total sannsynlighet`,
 d:String.raw`2.6 — \(P(A\cup B)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «gitt at» / «blant jentene» → betinget. <strong>Svar: B (4.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{P(\cap)}{P(\text{jente})}=\frac{0{,}2}{0{,}5}\).</div><div class="proc-step"><strong>2 —</strong> \(=0{,}4\).</div></div><div class="walk-note">Betingelsen krymper utfallsrommet til «jentene».</div>`},
{chapter:"Kap 4", correct:"C",
 q:String.raw`Du vet \(P(\text{pos}\mid\text{syk})=0{,}9\), \(P(\text{syk})=0{,}01\), \(P(\text{pos})=0{,}108\). Du vil <em>snu</em> betingelsen: \(P(\text{syk}\mid\text{pos})\). Hvilken formel?`,
 a:String.raw`4.1 — betinget`,
 b:String.raw`4.3 — total sannsynlighet`,
 c:String.raw`4.2 — \(P(B\mid A)=P(A\mid B)\cdot\frac{P(B)}{P(A)}\)`,
 d:String.raw`2.5 — komplement`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «snu betingelsen» → Bayes. <strong>Svar: C (4.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}9\cdot\frac{0{,}01}{0{,}108}\).</div><div class="proc-step"><strong>2 —</strong> \(\approx 0{,}083\).</div></div><div class="walk-note">Bayes bytter om hva som er gitt og hva vi spør om.</div>`},
{chapter:"Kap 4", correct:"A",
 q:String.raw`To fabrikker: \(B_1\) leverer 60 % (feilrate 5 %), \(B_2\) leverer 40 % (feilrate 10 %). Du vil ha total sannsynlighet for at en enhet er defekt. Hvilken formel?`,
 a:String.raw`4.3 — \(P(A)=\sum_i P(A\mid B_i)P(B_i)\)`,
 b:String.raw`4.1 — betinget`,
 c:String.raw`4.2 — Bayes`,
 d:String.raw`3.1 — \(N^s\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «total» over flere kilder → total sannsynlighet. <strong>Svar: A (4.3).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}05\cdot 0{,}6=0{,}03\).</div><div class="proc-step"><strong>2 —</strong> \(0{,}10\cdot 0{,}4=0{,}04\).</div><div class="proc-step"><strong>3 —</strong> sum: \(0{,}07\).</div></div><div class="walk-note">Vekt hver gren med hvor stor den er.</div>`},
{chapter:"Kap 4", correct:"C",
 q:String.raw`Du har \(P(A\cap B)=0{,}12\) og \(P(A)=0{,}3\), og vil ha \(P(B\mid A)\). Hvilken formel?`,
 a:String.raw`4.2 — Bayes`,
 b:String.raw`4.3 — total sannsynlighet`,
 c:String.raw`4.1 — \(P(B\mid A)=\frac{P(A\cap B)}{P(A)}\)`,
 d:String.raw`2.4 — modellkravet`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «gitt A», og du har snittet direkte → betinget. <strong>Svar: C (4.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{0{,}12}{0{,}3}=0{,}4\).</div></div><div class="walk-note">Har du snittet og betingelsen, trengs ikke Bayes.</div>`},
{chapter:"Kap 4", correct:"B",
 q:String.raw`<em>Mening.</em> Når er \(P(A\mid B)=P(A)\)?`,
 a:String.raw`Aldri`,
 b:String.raw`Når A og B er uavhengige — at B har skjedd endrer ikke sannsynligheten for A`,
 c:String.raw`Når A og B er disjunkte`,
 d:String.raw`Når \(P(B)=0\)`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Uavhengighet betyr at betingelsen ikke gir ny informasjon.</div><div class="walk-note">Disjunkt er det motsatte: vet du B, er A umulig.</div>`},
{chapter:"Kap 4", correct:"C",
 q:String.raw`<em>Hvorfor.</em> Testen var 90 % treffsikker, men \(P(\text{syk}\mid\text{pos})\approx 8\,\%\). Hvorfor så lavt?`,
 a:String.raw`Fordi testen var feil`,
 b:String.raw`Fordi vi regnet feil`,
 c:String.raw`Fordi sykdommen er svært sjelden (\(P(\text{syk})=0{,}01\)) — lav grunnrate gir mange falske positive`,
 d:String.raw`Fordi \(P(\text{pos})\) var for høy for Bayes`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> Når få faktisk er syke, drukner de ekte positive i de mange falske positive fra den store friske gruppa.</div><div class="walk-note">Grunnraten styrer svaret like mye som treffsikkerheten.</div>`}
];
