// HSM126 — Kjenn formelen. Kapittel 5 (tilfeldige variabler).
// Fordeling brukt flere steder: x=0,1,2,3 med P=0,1 / 0,3 / 0,4 / 0,2.
var KJ5 = [
{chapter:"Kap 5", correct:"B",
 q:String.raw`\(X\) har: \(x=0,1,2,3\) med \(P=0{,}1;\ 0{,}3;\ 0{,}4;\ 0{,}2\). I det lange løp — hva blir gjennomsnittlig utfall?`,
 a:String.raw`5.1 — \(P(X=x)\)`,
 b:String.raw`5.3 — \(E[X]=\sum x\cdot P(X=x)\)`,
 c:String.raw`5.5 — \(E[X^2]-(E[X])^2\)`,
 d:String.raw`5.6 — \(\sqrt{\operatorname{Var}[X]}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «i det lange løp», «gjennomsnittlig» → forventning. <strong>Svar: B (5.3).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0\cdot0{,}1+1\cdot0{,}3+2\cdot0{,}4+3\cdot0{,}2\).</div><div class="proc-step"><strong>2 —</strong> \(=1{,}7\).</div></div><div class="walk-note">Vektet snitt av verdiene.</div>`},
{chapter:"Kap 5", correct:"C",
 q:String.raw`Du vet \(E[X]=2\) og \(E[X^2]=5\). Du vil ha <em>variansen</em>. Hvilken formel?`,
 a:String.raw`5.3 — \(\sum x\cdot P(X=x)\)`,
 b:String.raw`5.6 — \(\sqrt{\operatorname{Var}[X]}\)`,
 c:String.raw`5.5 — \(\operatorname{Var}[X]=E[X^2]-(E[X])^2\)`,
 d:String.raw`5.9 — \(\operatorname{Var}[X]+\operatorname{Var}[Y]\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «varians» fra \(E[X]\) og \(E[X^2]\) → 5.5. <strong>Svar: C.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(5-2^2\).</div><div class="proc-step"><strong>2 —</strong> \(=1\).</div></div><div class="walk-note">Snitt av kvadratene minus kvadratet av snittet.</div>`},
{chapter:"Kap 5", correct:"A",
 q:String.raw`Du har \(\operatorname{Var}[X]=9\), men vil ha spredningen i <em>samme enhet</em> som X. Hvilken formel?`,
 a:String.raw`5.6 — \(\sqrt{\operatorname{Var}[X]}\)`,
 b:String.raw`5.5 — \(E[X^2]-(E[X])^2\)`,
 c:String.raw`5.3 — \(\sum x\cdot P(X=x)\)`,
 d:String.raw`5.8 — \(b^2\operatorname{Var}[X]\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «samme enhet» → standardavvik. <strong>Svar: A (5.6).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{9}=3\).</div></div><div class="walk-note">Variansen er i kvadrert enhet; rota gir tolkbar spredning.</div>`},
{chapter:"Kap 5", correct:"D",
 q:String.raw`Samme fordeling (\(0{,}1;0{,}3;0{,}4;0{,}2\) for \(x=0,1,2,3\)). Hva er \(P(X\le 1)\)?`,
 a:String.raw`5.1 — \(P(X=x)\)`,
 b:String.raw`5.3 — \(E[X]\)`,
 c:String.raw`5.5 — varians`,
 d:String.raw`5.2 — \(F(x)=P(X\le x)=\sum_{x_i\le x}P(X=x_i)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «\(\le\)», oppsamlet → kumulativ fordeling. <strong>Svar: D (5.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(P(0)+P(1)=0{,}1+0{,}3\).</div><div class="proc-step"><strong>2 —</strong> \(=0{,}4\).</div></div><div class="walk-note">Legg sammen alle utfall opp til og med x.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`Samme fordeling. Hva er sannsynligheten for at X er <em>nøyaktig</em> 2?`,
 a:String.raw`5.2 — \(F(x)=P(X\le x)\)`,
 b:String.raw`5.1 — \(P(X=x)\)`,
 c:String.raw`5.3 — \(\sum x\cdot P(X=x)\)`,
 d:String.raw`5.4 — \(\sum g(x)P(X=x)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «nøyaktig» → punktsannsynlighet. <strong>Svar: B (5.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> les av: \(P(X=2)=0{,}4\).</div></div><div class="walk-note">«Nøyaktig» = ett utfall (5.1). «\(\le\)» = oppsamlet (5.2).</div>`},
{chapter:"Kap 5", correct:"D",
 q:String.raw`\(E[X]=200\), og \(Y=2X+50\). Hva er \(E[Y]\)?`,
 a:String.raw`5.8 — \(b^2\operatorname{Var}[X]\)`,
 b:String.raw`5.5 — \(E[X^2]-(E[X])^2\)`,
 c:String.raw`5.3 — \(\sum x\cdot P(X=x)\)`,
 d:String.raw`5.7 — \(E[a+bX]=a+bE[X]\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> lineær omforming av forventning → 5.7. <strong>Svar: D.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(2\cdot200+50\).</div><div class="proc-step"><strong>2 —</strong> \(=450\).</div></div><div class="walk-note">Både skalering og konstant følger med i forventningen.</div>`},
{chapter:"Kap 5", correct:"A",
 q:String.raw`\(\operatorname{Var}[X]=16\), og \(Y=3X-4\). Hva er \(\operatorname{Var}[Y]\)?`,
 a:String.raw`5.8 — \(\operatorname{Var}[a+bX]=b^2\operatorname{Var}[X]\)`,
 b:String.raw`5.7 — \(a+bE[X]\)`,
 c:String.raw`5.9 — \(\operatorname{Var}[X]+\operatorname{Var}[Y]\)`,
 d:String.raw`5.6 — \(\sqrt{\operatorname{Var}[X]}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> lineær omforming av varians → 5.8. <strong>Svar: A.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> konstanten \(-4\) faller bort.</div><div class="proc-step"><strong>2 —</strong> \(3^2\cdot16=144\).</div></div><div class="walk-note">Konstanter flytter, ikke sprer; skaleringen kvadreres.</div>`},
{chapter:"Kap 5", correct:"C",
 q:String.raw`\(X,Y\) uavhengige, \(\operatorname{Var}[X]=4\), \(\operatorname{Var}[Y]=9\). Hva er \(\operatorname{Var}[X+Y]\)?`,
 a:String.raw`5.7 — \(a+bE[X]\)`,
 b:String.raw`5.5 — \(E[X^2]-(E[X])^2\)`,
 c:String.raw`5.9 — \(\operatorname{Var}[X+Y]=\operatorname{Var}[X]+\operatorname{Var}[Y]\)`,
 d:String.raw`5.8 — \(b^2\operatorname{Var}[X]\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «uavhengige» + sum → 5.9. <strong>Svar: C.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(4+9=13\).</div></div><div class="walk-note">Variansene legges sammen kun når variablene er uavhengige.</div>`},
{chapter:"Kap 5", correct:"B",
 q:String.raw`Samme fordeling. Du trenger \(E[X^2]\) — forventningen av X i andre. Hvilken formel?`,
 a:String.raw`5.3 — \(\sum x\cdot P(X=x)\)`,
 b:String.raw`5.4 — \(E[g(X)]=\sum g(x)P(X=x)\), med \(g(X)=X^2\)`,
 c:String.raw`5.5 — \(E[X^2]-(E[X])^2\)`,
 d:String.raw`5.1 — \(P(X=x)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> forventning av en <em>funksjon</em> av X → 5.4. <strong>Svar: B.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0+1\cdot0{,}3+4\cdot0{,}4+9\cdot0{,}2\).</div><div class="proc-step"><strong>2 —</strong> \(=3{,}7\).</div></div><div class="walk-note">5.4 mater \(E[X^2]\) inn i varians-snarveien 5.5.</div>`},
{chapter:"Kap 5", correct:"D",
 q:String.raw`<em>Mening.</em> Hva forteller variansen deg?`,
 a:String.raw`Det mest sannsynlige utfallet`,
 b:String.raw`Snittet i det lange løp`,
 c:String.raw`Den største verdien X kan ta`,
 d:String.raw`Hvor mye verdiene i snitt spriker fra forventningen`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D.</strong> Variansen måler spredning rundt \(E[X]\) — stor varians = mer uforutsigbart.</div><div class="walk-note">Snittet (B) er forventningen, ikke spredningen.</div>`},
{chapter:"Kap 5", correct:"A",
 q:String.raw`<em>Mening.</em> Hva betyr \(E[X]\) egentlig?`,
 a:String.raw`Snittet i det lange løp — balansepunktet i fordelinga`,
 b:String.raw`Det mest sannsynlige enkeltutfallet`,
 c:String.raw`Spredningen rundt snittet`,
 d:String.raw`Sannsynligheten for den høyeste verdien`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> Forventningen er det vektede snittet — der fordelinga balanserer.</div><div class="walk-note">Trenger ikke være et mulig utfall (her 1,7).</div>`},
{chapter:"Kap 5", correct:"C",
 q:String.raw`<em>Hvorfor.</em> Du har allerede variansen. Hvorfor regne ut standardavviket i tillegg?`,
 a:String.raw`Det er alltid et større tall`,
 b:String.raw`Det fjerner behovet for forventningen`,
 c:String.raw`Det er i samme enhet som X, så det er tolkbart`,
 d:String.raw`Det kan aldri bli negativt`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> Variansen er i kvadrert enhet; standardavviket bringer spredningen tilbake til X sin egen skala.</div><div class="walk-note">Derfor rapporteres spredning oftest som standardavvik.</div>`}
];
