// HSM126 — Kjenn formelen. Kapittel 6 (simultanfordeling).
// Tabell p(x,y): X=0 -> 0,10/0,20/0,10 ; X=1 -> 0,20/0,30/0,10  (Y=0,1,2).
var KJ6 = [
{chapter:"Kap 6", correct:"B",
 q:String.raw`Simultantabell \(p(x,y)\): rad \(X{=}0\): \(0{,}10;\ 0{,}20;\ 0{,}10\), rad \(X{=}1\): \(0{,}20;\ 0{,}30;\ 0{,}10\) (for \(Y{=}0,1,2\)). Du vil ha \(P(X{=}1\text{ og }Y{=}2)\) samtidig. Hvilken formel?`,
 a:String.raw`6.2 — \(P(X{=}x)=\sum_y p(x,y)\)`,
 b:String.raw`6.1 — \(p(x,y)=P(X{=}x,\,Y{=}y)\)`,
 c:String.raw`6.5 — \(E[XY]-E[X]E[Y]\)`,
 d:String.raw`6.4 — \(\sum_{x,y} h(x,y)\,p(x,y)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «og … samtidig» → simultan (felles celle). <strong>Svar: B (6.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> les cella \(X{=}1,\,Y{=}2\): \(0{,}10\).</div></div><div class="walk-note">Ett oppslag, ingen summering.</div>`},
{chapter:"Kap 6", correct:"D",
 q:String.raw`Samme tabell. Du vil ha \(P(X{=}0)\) <em>alene</em> — uansett hva \(Y\) er. Hvilken formel?`,
 a:String.raw`6.1 — \(p(x,y)\)`,
 b:String.raw`6.3 — \(P(Y{=}y)=\sum_x p(x,y)\)`,
 c:String.raw`6.6 — \(p(x,y)=P(X)P(Y)\)`,
 d:String.raw`6.2 — \(P(X{=}x)=\sum_y p(x,y)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «alene, uansett \(Y\)» → marginal for X. <strong>Svar: D (6.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> sum raden: \(0{,}10+0{,}20+0{,}10=0{,}40\).</div></div><div class="walk-note">Summer bort \(Y\) langs raden.</div>`},
{chapter:"Kap 6", correct:"A",
 q:String.raw`Samme tabell. Nå vil du ha \(P(Y{=}1)\) — uansett hva \(X\) er. Hvilken formel?`,
 a:String.raw`6.3 — \(P(Y{=}y)=\sum_x p(x,y)\)`,
 b:String.raw`6.2 — \(P(X{=}x)=\sum_y p(x,y)\)`,
 c:String.raw`6.1 — \(p(x,y)\)`,
 d:String.raw`6.4 — \(\sum_{x,y} h(x,y)\,p(x,y)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> marginal, men for \(Y\) → ned kolonnen. <strong>Svar: A (6.3).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> sum kolonnen: \(0{,}20+0{,}30=0{,}50\).</div></div><div class="walk-note">Summer bort \(X\) ned kolonnen.</div>`},
{chapter:"Kap 6", correct:"C",
 q:String.raw`Samme tabell. Du vil ha \(E[XY]\) — forventningen av <em>produktet</em>. Hvilken formel?`,
 a:String.raw`6.5 — \(E[XY]-E[X]E[Y]\)`,
 b:String.raw`6.1 — \(p(x,y)\)`,
 c:String.raw`6.4 — \(E[h(X,Y)]=\sum_{x,y} h(x,y)\,p(x,y)\), \(h{=}xy\)`,
 d:String.raw`6.2 — \(\sum_y p(x,y)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> forventning av en <em>funksjon</em> (\(xy\)) → 6.4. <strong>Svar: C.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> bare par der begge \(>0\): \(1{\cdot}1{\cdot}0{,}30+1{\cdot}2{\cdot}0{,}10\).</div><div class="proc-step"><strong>2 —</strong> \(=0{,}30+0{,}20=0{,}50\).</div></div><div class="walk-note">\(E[XY]\) er byggeklossen kovariansen bruker.</div>`},
{chapter:"Kap 6", correct:"B",
 q:String.raw`Gitt \(E[XY]=0{,}50\), \(E[X]=0{,}60\), \(E[Y]=0{,}90\). Du vil vite om \(X,Y\) <em>svinger sammen</em>. Hvilken formel?`,
 a:String.raw`6.6 — \(p(x,y)=P(X)P(Y)\)`,
 b:String.raw`6.5 — \(\operatorname{Cov}[X,Y]=E[XY]-E[X]E[Y]\)`,
 c:String.raw`6.4 — \(\sum_{x,y} h(x,y)\,p(x,y)\)`,
 d:String.raw`6.1 — \(p(x,y)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «svinger sammen» → kovarians. <strong>Svar: B (6.5).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(0{,}50-0{,}60{\cdot}0{,}90\).</div><div class="proc-step"><strong>2 —</strong> \(=0{,}50-0{,}54=-0{,}04\).</div></div><div class="walk-note">Negativt → ene høy, andre lav.</div>`},
{chapter:"Kap 6", correct:"D",
 q:String.raw`Samme tabell. Du vil sjekke om \(X\) og \(Y\) er <em>uavhengige</em>. Hvilken formel tester det?`,
 a:String.raw`6.5 — \(E[XY]-E[X]E[Y]\)`,
 b:String.raw`6.2 — \(\sum_y p(x,y)\)`,
 c:String.raw`6.4 — \(\sum_{x,y} h(x,y)\,p(x,y)\)`,
 d:String.raw`6.6 — \(p(x,y)=P(X{=}x)\cdot P(Y{=}y)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «uavhengige» → er felles lik produkt av marginaler? <strong>Svar: D (6.6).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(P(0,0)\): \(0{,}40{\cdot}0{,}30=0{,}12\).</div><div class="proc-step"><strong>2 —</strong> men cella er \(0{,}10\ne0{,}12\) → ikke uavhengige.</div></div><div class="walk-note">Bryter den for ett par, er de avhengige.</div>`},
{chapter:"Kap 6", correct:"A",
 q:String.raw`<em>Mening.</em> Kovariansen kom ut negativ. Hva forteller fortegnet?`,
 a:String.raw`Når den ene er høy, er den andre typisk lav`,
 b:String.raw`Variablene er uavhengige`,
 c:String.raw`Den ene er alltid større enn den andre`,
 d:String.raw`Summen av sannsynlighetene er under 1`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> Negativ kovarians = motsatt samvariasjon. Fortegnet leses først, størrelsen sier styrken.</div><div class="walk-note">Positiv = samme retning; nær null = svak sammenheng.</div>`},
{chapter:"Kap 6", correct:"C",
 q:String.raw`<em>Mening.</em> Hva betyr det at \(p(x,y)=P(X)P(Y)\) holder for <em>alle</em> \(x,y\)?`,
 a:String.raw`At \(X\) og \(Y\) alltid er like store`,
 b:String.raw`At summen av cellene er 1`,
 c:String.raw`At \(X\) og \(Y\) er uavhengige`,
 d:String.raw`At de har samme forventning`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> Felles lik produkt av marginaler = uavhengighet: den ene sier ingenting om den andre.</div><div class="walk-note">B gjelder enhver fordeling, ikke bare uavhengige.</div>`},
{chapter:"Kap 6", correct:"B",
 q:String.raw`<em>Hvorfor.</em> Hvorfor «summerer vi bort» den ene variabelen i en marginalfordeling?`,
 a:String.raw`For å spare regnetid`,
 b:String.raw`Vi vil ha oppførselen til én variabel alene, uansett hva den andre gjør`,
 c:String.raw`Fordi summen alltid må bli 1`,
 d:String.raw`Fordi variablene må være uavhengige`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Marginalen folder bort den andre dimensjonen: sum langs rad (X) eller kolonne (Y).</div><div class="walk-note">Totalsannsynlighet for den ene, samme hva den andre lander på.</div>`}
];
