// HSM126 — Kjenn formelen. Kapittel 7 (sentrale fordelinger).
var KJ7 = [
{chapter:"Kap 7", correct:"C",
 q:String.raw`\(n{=}10\) uavhengige forsøk <em>med tilbakelegging</em>, samme \(p{=}0{,}3\). Du teller suksesser og vil ha \(P(X{=}4)\). Hvilken fordeling?`,
 a:String.raw`7.3.1 — \(\frac{\lambda^x}{x!}e^{-\lambda}\)`,
 b:String.raw`7.2 — \(\frac{\binom{M}{x}\binom{N-M}{n-x}}{\binom{N}{n}}\)`,
 c:String.raw`7.1.1 — \(\binom{n}{x}p^x(1-p)^{n-x}\)`,
 d:String.raw`7.5 — \(G(b)-G(a)\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «fast \(n\), med tilbakelegging, samme \(p\)» → binomisk. <strong>Svar: C (7.1.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\binom{10}{4}{\cdot}0{,}3^4{\cdot}0{,}7^6\approx0{,}200\).</div></div><div class="walk-note">\(\binom{n}{x}\) teller måtene; potensene gir hver måtes sjanse.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`Eske: \(N{=}20\), \(M{=}8\) defekte. Du trekker \(n{=}5\) <em>uten tilbakelegging</em> og vil ha \(P(x{=}2)\) defekte. Hvilken fordeling?`,
 a:String.raw`7.2 — \(\frac{\binom{M}{x}\binom{N-M}{n-x}}{\binom{N}{n}}\)`,
 b:String.raw`7.1.1 — \(\binom{n}{x}p^x(1-p)^{n-x}\)`,
 c:String.raw`7.3.1 — \(\frac{\lambda^x}{x!}e^{-\lambda}\)`,
 d:String.raw`7.7 — \(np(1-p)\ge 5\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «uten tilbakelegging, endelig beholdning» → hypergeometrisk. <strong>Svar: A (7.2).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{\binom{8}{2}\binom{12}{3}}{\binom{20}{5}}=\frac{6160}{15504}\approx0{,}397\).</div></div><div class="walk-note">Hvert trekk endrer beholdningen — derfor ikke binomisk.</div>`},
{chapter:"Kap 7", correct:"D",
 q:String.raw`Et kundesenter får i snitt \(\lambda{=}3\) samtaler per minutt — sjeldne, uavhengige hendelser. \(P(X{=}5)\) på ett minutt. Hvilken fordeling?`,
 a:String.raw`7.1.1 — \(\binom{n}{x}p^x(1-p)^{n-x}\)`,
 b:String.raw`7.5 — \(G(b)-G(a)\)`,
 c:String.raw`7.2 — \(\frac{\binom{M}{x}\binom{N-M}{n-x}}{\binom{N}{n}}\)`,
 d:String.raw`7.3.1 — \(\frac{\lambda^x}{x!}e^{-\lambda}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «snitt per intervall, ingen fast \(n\)» → Poisson. <strong>Svar: D (7.3.1).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{3^5}{5!}e^{-3}\approx0{,}101\).</div></div><div class="walk-note">Bare \(\lambda\) styrer hele fordelinga.</div>`},
{chapter:"Kap 7", correct:"B",
 q:String.raw`Binomisk med \(n{=}50\), \(p{=}0{,}2\). Du vil ha <em>variansen</em> til antall suksesser. Hvilken formel?`,
 a:String.raw`7.1.2 — \(E[X]=np\)`,
 b:String.raw`7.1.3 — \(\operatorname{Var}[X]=np(1-p)\)`,
 c:String.raw`7.3.2 — \(\operatorname{Var}[X]=\lambda\)`,
 d:String.raw`5.8 — \(b^2\operatorname{Var}[X]\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «varians» i en <em>binomisk</em> → 7.1.3. <strong>Svar: B.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(50{\cdot}0{,}2{\cdot}0{,}8=8\).</div></div><div class="walk-note">Fella: \(np=10\) er forventningen, ikke variansen.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`\(X\) er normalfordelt med \(E[X]=100\), \(\sigma=15\). For \(P(X\le 120)\) må du først til standard normal. Hvilken formel?`,
 a:String.raw`7.8 — \(\frac{s-E[S]}{\sigma[S]}\)`,
 b:String.raw`7.1.1 — \(\binom{n}{x}p^x(1-p)^{n-x}\)`,
 c:String.raw`7.5 — \(G(b)-G(a)\)`,
 d:String.raw`7.3.1 — \(\frac{\lambda^x}{x!}e^{-\lambda}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «gjøre om til standard normal» → standardisering. <strong>Svar: A (7.8).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{120-100}{15}\approx1{,}33\).</div></div><div class="walk-note">Så slår du opp \(G(1{,}33)\) i tabell.</div>`},
{chapter:"Kap 7", correct:"C",
 q:String.raw`Du har standardisert og vil ha \(P(-1\le Z\le 1{,}5)\). Hvilken formel?`,
 a:String.raw`7.8 — \(\frac{s-E[S]}{\sigma[S]}\)`,
 b:String.raw`7.4 — \(N[0,1]\)`,
 c:String.raw`7.5 — \(P(a\le X\le b)=G(b)-G(a)\)`,
 d:String.raw`7.9 — \(\frac{s+0{,}5-E[S]}{\sigma[S]}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «mellom to verdier» → areal mellom \(a\) og \(b\). <strong>Svar: C (7.5).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(G(1{,}5)-G(-1)\approx0{,}933-0{,}159=0{,}774\).</div></div><div class="walk-note">\(G(-z)=1-G(z)\) for den negative enden.</div>`},
{chapter:"Kap 7", correct:"B",
 q:String.raw`Binomisk \(n{=}40\), \(p{=}0{,}3\). Hvilken sjekk avgjør om normaltilnærming er forsvarlig?`,
 a:String.raw`7.6 — sentralgrensesetningen`,
 b:String.raw`7.7 — \(np(1-p)\ge 5\)`,
 c:String.raw`7.1.1 — \(\binom{n}{x}p^x(1-p)^{n-x}\)`,
 d:String.raw`7.9 — \(\frac{s+0{,}5-E[S]}{\sigma[S]}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «kan jeg tilnærme med normal» → tilnærmingskriteriet. <strong>Svar: B (7.7).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(40{\cdot}0{,}3{\cdot}0{,}7=8{,}4\ge5\) → brukbar.</div></div><div class="walk-note">\(\ge10\) ville vært «god».</div>`},
{chapter:"Kap 7", correct:"D",
 q:String.raw`Du tilnærmer binomisk \((n{=}40,p{=}0{,}3)\) med normal og vil ha \(P(X\le 18)\). \(X\) er heltall. Beste tilnærming?`,
 a:String.raw`7.8 — \(\frac{s-E[S]}{\sigma[S]}\) (uten korreksjon)`,
 b:String.raw`7.5 — \(G(b)-G(a)\)`,
 c:String.raw`7.3.1 — \(\frac{\lambda^x}{x!}e^{-\lambda}\)`,
 d:String.raw`7.9 — \(\frac{s+0{,}5-E[S]}{\sigma[S]}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «heltall mot kontinuerlig normal» → heltallskorreksjon. <strong>Svar: D (7.9).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{18{,}5-12}{2{,}90}\approx2{,}24\) (\(E{=}12\), \(\sigma{=}\sqrt{8{,}4}\)).</div></div><div class="walk-note">\(+0{,}5\) dekker hele heltallssøyla.</div>`},
{chapter:"Kap 7", correct:"A",
 q:String.raw`<em>Mening.</em> Avgjørende forskjell mellom binomisk (7.1) og hypergeometrisk (7.2)?`,
 a:String.raw`Binomisk: med tilbakelegging, konstant \(p\); hypergeometrisk: uten tilbakelegging, \(p\) endres`,
 b:String.raw`Binomisk gjelder bare myntkast`,
 c:String.raw`Hypergeometrisk har alltid færre steg`,
 d:String.raw`De gir alltid samme svar`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> Tilbakelegging = uavhengige forsøk med samme \(p\); uten = endelig beholdning som tømmes.</div><div class="walk-note">\(N\ge20n\): hypergeometrisk nærmer seg binomisk.</div>`},
{chapter:"Kap 7", correct:"C",
 q:String.raw`<em>Mening.</em> Når passer Poisson (7.3) best?`,
 a:String.raw`Fast antall forsøk med to utfall`,
 b:String.raw`Trekking uten tilbakelegging`,
 c:String.raw`Sjeldne, uavhengige hendelser over et intervall, kjent snittrate \(\lambda\)`,
 d:String.raw`Data som allerede er normalfordelte`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> Poisson teller hendelser i et intervall; \(E[X]=\operatorname{Var}[X]=\lambda\).</div><div class="walk-note">A = binomisk, B = hypergeometrisk.</div>`},
{chapter:"Kap 7", correct:"B",
 q:String.raw`<em>Hvorfor.</em> Hvorfor standardiserer vi (7.8) før tabelloppslag?`,
 a:String.raw`Det gir et større tall`,
 b:String.raw`Tabellen finnes bare for standard normal \(N[0,1]\) — vi oversetter til felles z-skala`,
 c:String.raw`Variansen forsvinner`,
 d:String.raw`Heltallskorreksjon krever det`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Uendelig mange normalfordelinger, men én tabell — z-skalaen dekker alt.</div><div class="walk-note">Derfor kommer 7.8 rett før et oppslag \(G(z)\).</div>`}
];
