// HSM126 — Kjenn formelen. Kapittel 8 (estimering).
var KJ8 = [
{chapter:"Kap 8", correct:"A",
 q:String.raw`\(n{=}25\), \(\bar X{=}50\), \(S_X{=}10\). Du vil oppgi anslaget for snittet <em>pluss/minus standardfeilen</em> (ikke et 95%-intervall). Hvilken formel?`,
 a:String.raw`8.4 — \(\bar X\pm\frac{S_X}{\sqrt n}\)`,
 b:String.raw`8.5 — \(\hat p\pm\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 c:String.raw`8.10 — \(\bar X\pm t^{(n-1)}_{\alpha/2}\frac{S_X}{\sqrt n}\)`,
 d:String.raw`8.3 — \(\bar X\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «snitt ± standardfeil», ingen konfidensgrad → 8.4. <strong>Svar: A.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{10}{\sqrt{25}}=2\) → \(50\pm2\).</div></div><div class="walk-note">Ingen 1,96/t før du vil ha et bestemt konfidensnivå.</div>`},
{chapter:"Kap 8", correct:"C",
 q:String.raw`\(n{=}100\), \(\hat p{=}0{,}40\). Du vil oppgi andelen <em>pluss/minus standardfeilen</em>. Hvilken formel?`,
 a:String.raw`8.4 — \(\bar X\pm\frac{S_X}{\sqrt n}\)`,
 b:String.raw`8.9 — \(\bar X\pm1{,}96\frac{S_X}{\sqrt n}\)`,
 c:String.raw`8.5 — \(\hat p\pm\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 d:String.raw`8.8 — \(\hat p\pm1{,}96\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «andel ± standardfeil» → 8.5. <strong>Svar: C.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\sqrt{\frac{0{,}40{\cdot}0{,}60}{100}}\approx0{,}049\).</div></div><div class="walk-note">Andel → \(\hat p(1-\hat p)\) i telleren, ikke \(S_X\).</div>`},
{chapter:"Kap 8", correct:"B",
 q:String.raw`\(n{=}64\) (stort utvalg), \(\bar X{=}100\), \(S_X{=}16\). Du vil ha et <em>95%</em> konfidensintervall for snittet. Hvilken formel?`,
 a:String.raw`8.4 — \(\bar X\pm\frac{S_X}{\sqrt n}\)`,
 b:String.raw`8.9 — \(\bar X\pm1{,}96\frac{S_X}{\sqrt n}\)`,
 c:String.raw`8.10 — \(\bar X\pm t^{(n-1)}_{\alpha/2}\frac{S_X}{\sqrt n}\)`,
 d:String.raw`8.8 — \(\hat p\pm1{,}96\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «95%, snitt, stort \(n\)» → z-intervall. <strong>Svar: B (8.9).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1{,}96{\cdot}\frac{16}{8}=3{,}92\) → \(100\pm3{,}92\).</div></div><div class="walk-note">Stort \(n\) → z holder; lite \(n\) → t (8.10).</div>`},
{chapter:"Kap 8", correct:"D",
 q:String.raw`\(n{=}200\), \(\hat p{=}0{,}25\). Du vil ha et <em>95%</em> konfidensintervall for andelen. Hvilken formel?`,
 a:String.raw`8.5 — \(\hat p\pm\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 b:String.raw`8.9 — \(\bar X\pm1{,}96\frac{S_X}{\sqrt n}\)`,
 c:String.raw`8.10 — \(\bar X\pm t^{(n-1)}_{\alpha/2}\frac{S_X}{\sqrt n}\)`,
 d:String.raw`8.8 — \(\hat p\pm1{,}96\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «95%, andel» → 8.8. <strong>Svar: D.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1{,}96{\cdot}\sqrt{\frac{0{,}25{\cdot}0{,}75}{200}}\approx0{,}060\).</div></div><div class="walk-note">8.5 er bare ± standardfeil; 8.8 ganger inn 1,96.</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`Normalfordelt, <em>lite</em> utvalg \(n{=}10\), \(\bar X{=}20\), \(S_X{=}4\). Du vil ha et 95% konfidensintervall for snittet. Hvilken formel?`,
 a:String.raw`8.10 — \(\bar X\pm t^{(n-1)}_{\alpha/2}\frac{S_X}{\sqrt n}\)`,
 b:String.raw`8.9 — \(\bar X\pm1{,}96\frac{S_X}{\sqrt n}\)`,
 c:String.raw`8.5 — \(\hat p\pm\sqrt{\frac{\hat p(1-\hat p)}{n}}\)`,
 d:String.raw`8.4 — \(\bar X\pm\frac{S_X}{\sqrt n}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «lite \(n\), \(\sigma\) ukjent» → t-intervall. <strong>Svar: A (8.10).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(t^{9}_{0{,}025}=2{,}262\); \(2{,}262{\cdot}\frac{4}{\sqrt{10}}\approx2{,}86\).</div></div><div class="walk-note">t er bredere enn z — betaler for lite utvalg.</div>`},
{chapter:"Kap 8", correct:"C",
 q:String.raw`Du skal lage et <em>99%</em>-intervall (stort utvalg). Hvilken kritisk z-verdi hører til?`,
 a:String.raw`\(1{,}645\) (90%)`,
 b:String.raw`\(1{,}96\) (95%)`,
 c:String.raw`\(2{,}58\) (99%)`,
 d:String.raw`\(1{,}28\) (80%)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «99%» → \(z_{0{,}005}\). <strong>Svar: C (8.7).</strong></div><div class="walk-note">90/95/99 → 1,645 / 1,96 / 2,58. Høyere tillit → bredere intervall.</div>`},
{chapter:"Kap 8", correct:"B",
 q:String.raw`Du trekker \(n{=}10\) <em>uten tilbakelegging</em> fra en endelig populasjon \(N{=}100\), \(\sigma^2{=}25\). Du vil ha variansen til snittet med endelig-populasjon-korreksjon. Hvilken formel?`,
 a:String.raw`8.9 — \(\bar X\pm1{,}96\frac{S_X}{\sqrt n}\)`,
 b:String.raw`8.11 — \(\frac{N-n}{N-1}\cdot\frac{\sigma^2}{n}\)`,
 c:String.raw`7.2 — hypergeometrisk`,
 d:String.raw`8.4 — \(\bar X\pm\frac{S_X}{\sqrt n}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «endelig populasjon, uten tilbakelegging» → korreksjonsfaktor. <strong>Svar: B (8.11).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{90}{99}{\cdot}\frac{25}{10}\approx2{,}27\).</div></div><div class="walk-note">\(\frac{N-n}{N-1}<1\) krymper variansen.</div>`},
{chapter:"Kap 8", correct:"D",
 q:String.raw`<em>Mening.</em> Hva betyr det at en estimator er <em>forventningsrett</em>?`,
 a:String.raw`Den treffer alltid eksakt`,
 b:String.raw`Den har minst mulig varians`,
 c:String.raw`Den krever stort utvalg`,
 d:String.raw`I snitt over mange utvalg treffer den den sanne verdien`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: D.</strong> Forventningsrett: \(E[\hat\theta]=\theta\) — ingen systematisk skjevhet, ikke at hvert enkelt anslag er perfekt.</div><div class="walk-note">Liten varians (B) er en separat, ønsket egenskap.</div>`},
{chapter:"Kap 8", correct:"A",
 q:String.raw`<em>Hvorfor.</em> Hvorfor står \(\sqrt n\) i nevneren for standardfeilen?`,
 a:String.raw`Større utvalg → snittet svinger mindre, så feilen krymper med \(\sqrt n\)`,
 b:String.raw`For å gjøre tallet større`,
 c:String.raw`Fordi \(p\) må ligge mellom 0 og 1`,
 d:String.raw`Det er bare en konvensjon uten grunn`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: A.</strong> Standardfeil \(=S_X/\sqrt n\): mer data stabiliserer snittet, men avtakende (firedoble \(n\) → halver feilen).</div><div class="walk-note">Derfor er det dyrt å halvere usikkerheten.</div>`},
{chapter:"Kap 8", correct:"C",
 q:String.raw`<em>Hvorfor.</em> Hvorfor t-fordeling i stedet for z når utvalget er lite?`,
 a:String.raw`t gir alltid smalere intervall`,
 b:String.raw`z finnes ikke for små tall`,
 c:String.raw`Vi anslår \(\sigma\) med \(S_X\); t har tyngre haler og tar høyde for den ekstra usikkerheten`,
 d:String.raw`t krever at dataene ikke er normale`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> Ukjent \(\sigma\) anslag → mer usikkerhet → bredere t. Med stort \(n\) nærmer t seg z.</div><div class="walk-note">Derfor faller t-leddet bort i 8.9.</div>`},
{chapter:"Kap 8", correct:"B",
 q:String.raw`<em>Mening.</em> Et 95% konfidensintervall ble \([46;\,54]\). Hva betyr «95%»?`,
 a:String.raw`Det er 95% sjanse for at akkurat dette intervallet inneholder \(\mu\)`,
 b:String.raw`Metoden fanger \(\mu\) i 95% av slike utvalg i det lange løp`,
 c:String.raw`95% av dataene ligger i intervallet`,
 d:String.raw`Snittet er 95`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Tilliten ligger i <em>prosedyren</em>, ikke i ett enkelt intervall (som enten inneholder \(\mu\) eller ikke).</div><div class="walk-note">Vanlig felle: A blander hyppighet og enkelthendelse.</div>`}
];
