// HSM126 — Kjenn formelen. Kapittel 9 (hypotesetesting, grunnlag).
var KJ9 = [
{chapter:"Kap 9", correct:"A",
 q:String.raw`\(S_{\hat\theta}{=}20\), \(n{=}100\). Du vil ha standardfeilen til estimatoren. Hvilken formel?`,
 a:String.raw`9.9 — \(se=\frac{S_{\hat\theta}}{\sqrt n}\)`,
 b:String.raw`9.8 — \(t_{TS}=\frac{\hat\theta-\theta_0}{se}\)`,
 c:String.raw`8.4 — \(\bar X\pm\frac{S_X}{\sqrt n}\)`,
 d:String.raw`9.2 — signifikansnivå \(\alpha\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «standardfeil til estimatoren» → 9.9. <strong>Svar: A.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{20}{\sqrt{100}}=2\).</div></div><div class="walk-note">\(se\) er nevneren i testobservatoren etterpå.</div>`},
{chapter:"Kap 9", correct:"D",
 q:String.raw`\(\bar X{=}152\), \(H_0:\mu{=}150\), \(se{=}0{,}913\). Du vil ha selve testobservatoren. Hvilken formel?`,
 a:String.raw`9.9 — \(se=\frac{S_{\hat\theta}}{\sqrt n}\)`,
 b:String.raw`9.5 — tosidet forkastning`,
 c:String.raw`9.4 — P-verdi`,
 d:String.raw`9.8 — \(t_{TS}=\frac{\hat\theta-\theta_0}{se}\)`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «hvor mange standardfeil fra \(\theta_0\)» → testobservator. <strong>Svar: D (9.8).</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(\frac{152-150}{0{,}913}\approx2{,}19\).</div></div><div class="walk-note">Avstand målt i standardfeil; \(se\) (9.9) må være klar først.</div>`},
{chapter:"Kap 9", correct:"C",
 q:String.raw`Spørsmålet er om verdien «skiller seg fra» 150 — begge retninger teller. Hvilken oppsett?`,
 a:String.raw`9.7 — ensidet, øvre hale`,
 b:String.raw`9.6 — ensidet, nedre hale`,
 c:String.raw`9.5 — tosidet: \(|t_{TS}|>z_{\alpha/2}\)`,
 d:String.raw`9.1 — elementene i en test`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «skiller seg fra» → tosidet. <strong>Svar: C (9.5).</strong></div><div class="walk-note">Deler \(\alpha\) i to haler; sammenlign \(|t_{TS}|\) med \(z_{\alpha/2}\).</div>`},
{chapter:"Kap 9", correct:"A",
 q:String.raw`Påstanden er at verdien er <em>større enn</em> 150. Hvilken oppsett?`,
 a:String.raw`9.7 — ensidet øvre: \(t_{TS}>z_{\alpha}\)`,
 b:String.raw`9.5 — tosidet`,
 c:String.raw`9.6 — ensidet nedre: \(t_{TS}<-z_{\alpha}\)`,
 d:String.raw`9.3 — styrke`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «større enn» → ensidet øvre. <strong>Svar: A (9.7).</strong></div><div class="walk-note">Hele \(\alpha\) i øvre hale → \(z_{\alpha}\), ikke \(z_{\alpha/2}\).</div>`},
{chapter:"Kap 9", correct:"B",
 q:String.raw`Påstanden er at verdien er <em>mindre enn</em> 150. Hvilken oppsett?`,
 a:String.raw`9.7 — ensidet øvre`,
 b:String.raw`9.6 — ensidet nedre: \(t_{TS}<-z_{\alpha}\)`,
 c:String.raw`9.5 — tosidet`,
 d:String.raw`9.4 — P-verdi`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «mindre enn» → ensidet nedre. <strong>Svar: B (9.6).</strong></div><div class="walk-note">Forkast for sterkt negativ \(t_{TS}\).</div>`},
{chapter:"Kap 9", correct:"C",
 q:String.raw`Du vil sette risikoen for å forkaste en sann \(H_0\) (type I) til 5%. Hva er dette?`,
 a:String.raw`9.4 — P-verdi`,
 b:String.raw`9.3 — styrke \(\gamma\)`,
 c:String.raw`9.2 — signifikansnivå \(\alpha\)`,
 d:String.raw`9.1 — elementene`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «risiko for type I, fast før data» → \(\alpha\). <strong>Svar: C (9.2).</strong></div><div class="walk-note">\(\alpha\) settes på forhånd; P-verdien regnes ut etter.</div>`},
{chapter:"Kap 9", correct:"D",
 q:String.raw`Du vil ha sannsynligheten for et resultat <em>minst så ekstremt</em> som det observerte, gitt \(H_0\). Hva er det?`,
 a:String.raw`9.2 — signifikansnivå`,
 b:String.raw`9.3 — styrke`,
 c:String.raw`9.5 — tosidet forkastning`,
 d:String.raw`9.4 — P-verdi`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «minst så ekstremt gitt \(H_0\)» → P-verdi. <strong>Svar: D (9.4).</strong></div><div class="walk-note">Forkast når \(P<\alpha\).</div>`},
{chapter:"Kap 9", correct:"A",
 q:String.raw`Du har \(\beta{=}0{,}20\) (type II-risiko) og vil ha <em>styrken</em>. Hvilken formel?`,
 a:String.raw`9.3 — \(\gamma=1-\beta\)`,
 b:String.raw`9.2 — \(\alpha\)`,
 c:String.raw`9.9 — \(se\)`,
 d:String.raw`9.4 — P-verdi`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «styrke fra \(\beta\)» → 9.3. <strong>Svar: A.</strong></div><div class="proc-block"><div class="proc-title">Steg</div><div class="proc-step"><strong>1 —</strong> \(1-0{,}20=0{,}80\).</div></div><div class="walk-note">Styrke = sjansen for å oppdage en reell effekt.</div>`},
{chapter:"Kap 9", correct:"B",
 q:String.raw`Du skal liste hva en hypotesetest faktisk består av (\(H_0\), \(H_1\), testobservator, forkastningsregel, konklusjon). Hvilket punkt?`,
 a:String.raw`9.8 — testobservator`,
 b:String.raw`9.1 — elementene i en hypotesetest`,
 c:String.raw`9.5 — tosidet`,
 d:String.raw`10.8 — stegrekkefølge i praksis`,
 walk:String.raw`<div class="walk-intro"><strong>Avgjør:</strong> «ramme/består av» → 9.1. <strong>Svar: B.</strong></div><div class="walk-note">9.1 er kartet; resten er enkeltverktøy.</div>`},
{chapter:"Kap 9", correct:"C",
 q:String.raw`<em>Mening.</em> P-verdien ble \(0{,}02\) og \(\alpha{=}0{,}05\). Hva gjør du?`,
 a:String.raw`Beholder \(H_0\), for \(0{,}02\) er lite`,
 b:String.raw`Kan ikke konkludere`,
 c:String.raw`Forkaster \(H_0\): \(P<\alpha\)`,
 d:String.raw`Øker \(\alpha\) til resultatet stemmer`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: C.</strong> \(P<\alpha\) → forkast. Liten P = data lite forenlig med \(H_0\).</div><div class="walk-note">D er å jukse med terskelen i etterkant.</div>`},
{chapter:"Kap 9", correct:"B",
 q:String.raw`<em>Hvorfor.</em> Hvorfor deler vi \(\alpha\) på 2 i en tosidet test?`,
 a:String.raw`For å gjøre testen strengere uten grunn`,
 b:String.raw`Fordi en ekstrem verdi kan ligge i begge haler — risikoen fordeles likt`,
 c:String.raw`Fordi \(se\) er halvert`,
 d:String.raw`Fordi data alltid er symmetriske`,
 walk:String.raw`<div class="walk-intro"><strong>Svar: B.</strong> Tosidet: avvik teller begge veier, så \(\alpha\) splittes — \(\alpha/2\) i hver hale → \(z_{\alpha/2}\).</div><div class="walk-note">Ensidet legger hele \(\alpha\) i én hale.</div>`}
];
